package com.gwac.model2;
// Generated 2015-1-31 21:02:51 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cvs generated by hbm2java
 */
@Entity
@Table(name = "variable_catalogue",
	 catalog = "catalogue"
)
public class VariableCatalogue implements java.io.Serializable {

  private Integer id;
  private String name;
  private String auid;
  private Float radeg;
  private Float dedeg;
  private String constStr;
  private String type;
  private Float period;
  private Float mag1;
  private Float mag2;
  private String filter;
  private String note;

  public VariableCatalogue() {
  }

  /**
   * @return the id
   */
  @Id
  @GeneratedValue(strategy = IDENTITY)
  @Column(name = "id", unique = true, nullable = false)
  public Integer getId() {
    return id;
  }

  /**
   * @param id the id to set
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * @return the name
   */
  @Column(name = "name")
  public String getName() {
    return name;
  }

  /**
   * @param name the name to set
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * @return the auid
   */
  @Column(name = "auid")
  public String getAuid() {
    return auid;
  }

  /**
   * @param auid the auid to set
   */
  public void setAuid(String auid) {
    this.auid = auid;
  }

  /**
   * @return the radeg
   */
  @Column(name = "radeg")
  public Float getRadeg() {
    return radeg;
  }

  /**
   * @param radeg the radeg to set
   */
  public void setRadeg(Float radeg) {
    this.radeg = radeg;
  }

  /**
   * @return the dedeg
   */
  @Column(name = "decdeg")
  public Float getDedeg() {
    return dedeg;
  }

  /**
   * @param dedeg the dedeg to set
   */
  public void setDedeg(Float dedeg) {
    this.dedeg = dedeg;
  }

  /**
   * @return the constStr
   */
  @Column(name = "const")
  public String getConstStr() {
    return constStr;
  }

  /**
   * @param constStr the constStr to set
   */
  public void setConstStr(String constStr) {
    this.constStr = constStr;
  }

  /**
   * @return the type
   */
  @Column(name = "type")
  public String getType() {
    return type;
  }

  /**
   * @param type the type to set
   */
  public void setType(String type) {
    this.type = type;
  }

  /**
   * @return the period
   */
  @Column(name = "period")
  public Float getPeriod() {
    return period;
  }

  /**
   * @param period the period to set
   */
  public void setPeriod(Float period) {
    this.period = period;
  }

  /**
   * @return the mag1
   */
  @Column(name = "mag_1")
  public Float getMag1() {
    return mag1;
  }

  /**
   * @param mag1 the mag1 to set
   */
  public void setMag1(Float mag1) {
    this.mag1 = mag1;
  }

  /**
   * @return the mag2
   */
  @Column(name = "mag_2")
  public Float getMag2() {
    return mag2;
  }

  /**
   * @param mag2 the mag2 to set
   */
  public void setMag2(Float mag2) {
    this.mag2 = mag2;
  }

  /**
   * @return the filter
   */
  @Column(name = "filter")
  public String getFilter() {
    return filter;
  }

  /**
   * @param filter the filter to set
   */
  public void setFilter(String filter) {
    this.filter = filter;
  }

  /**
   * @return the note
   */
  @Column(name = "note")
  public String getNote() {
    return note;
  }

  /**
   * @param note the note to set
   */
  public void setNote(String note) {
    this.note = note;
  }

}
