package com.gwac.model2;
// Generated 2015-1-31 21:02:51 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MinorPlanet8 generated by hbm2java
 */
@Entity
@Table(name = "aoop_longlat_56968", catalog = "catalogue"
)
public class MinorPlanet implements java.io.Serializable {

  private Integer idnum;
  private String mpid;
  private Float mjd;
  private Float lon;
  private Float lat;
  private Float dlon;
  private Float dlat;
  private Float vmag;

  public MinorPlanet() {
  }

  public MinorPlanet(String mpid, Float mjd, Float lon, Float lat, Float dlon, Float dlat, Float vmag) {
    this.mpid = mpid;
    this.mjd = mjd;
    this.lon = lon;
    this.lat = lat;
    this.dlon = dlon;
    this.dlat = dlat;
    this.vmag = vmag;
  }

  @Id
  @GeneratedValue(strategy = IDENTITY)

  @Column(name = "IDNUM", unique = true, nullable = false)
  public Integer getIdnum() {
    return this.idnum;
  }

  public void setIdnum(Integer idnum) {
    this.idnum = idnum;
  }

  @Column(name = "MPID", length = 10)
  public String getMpid() {
    return this.mpid;
  }

  public void setMpid(String mpid) {
    this.mpid = mpid;
  }

  @Column(name = "MJD", precision = 8)
  public Float getMjd() {
    return this.mjd;
  }

  public void setMjd(Float mjd) {
    this.mjd = mjd;
  }

  @Column(name = "LON", precision = 10, scale = 6)
  public Float getLon() {
    return this.lon;
  }

  public void setLon(Float lon) {
    this.lon = lon;
  }

  @Column(name = "LAT", precision = 10, scale = 6)
  public Float getLat() {
    return this.lat;
  }

  public void setLat(Float lat) {
    this.lat = lat;
  }

  @Column(name = "DLON", precision = 10, scale = 6)
  public Float getDlon() {
    return this.dlon;
  }

  public void setDlon(Float dlon) {
    this.dlon = dlon;
  }

  @Column(name = "DLAT", precision = 10, scale = 6)
  public Float getDlat() {
    return this.dlat;
  }

  public void setDlat(Float dlat) {
    this.dlat = dlat;
  }

  /**
   * @return the vmag
   */
  @Column(name = "VMAG", precision = 10, scale = 6)
  public Float getVmag() {
    return vmag;
  }

  /**
   * @param vmag the vmag to set
   */
  public void setVmag(Float vmag) {
    this.vmag = vmag;
  }

}
