package com.gwac.model;
// Generated 2014-9-1 13:05:37 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ConfigFile generated by hbm2java
 */
@Entity
@Table(name = "config_file", schema = "public"
)
public class ConfigFile implements java.io.Serializable {

  private long cfId;
  private String fileName;
  private Boolean isStore;
  private Boolean isSync;
  private String storePath;

  public ConfigFile() {
  }

  public ConfigFile(String fileName, Boolean isStore, Boolean isSync, String storePath) {
    this.fileName = fileName;
    this.isStore = isStore;
    this.isSync = isSync;
    this.storePath = storePath;
  }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "cf_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "cf_id", unique = true, nullable = false)
  public long getCfId() {
    return this.cfId;
  }

  public void setCfId(long cfId) {
    this.cfId = cfId;
  }

  @Column(name = "file_name")
  public String getFileName() {
    return this.fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  @Column(name = "is_store")
  public Boolean getIsStore() {
    return this.isStore;
  }

  public void setIsStore(Boolean isStore) {
    this.isStore = isStore;
  }

  @Column(name = "is_sync")
  public Boolean getIsSync() {
    return this.isSync;
  }

  public void setIsSync(Boolean isSync) {
    this.isSync = isSync;
  }

  @Column(name = "store_path")
  public String getStorePath() {
    return this.storePath;
  }

  public void setStorePath(String storePath) {
    this.storePath = storePath;
  }

}
