package com.gwac.model;
// Generated Feb 14, 2014 3:32:17 PM by Hibernate Tools 3.2.2.GA



/**
 * DataProcessMachine generated by hbm2java
 */
public class DataProcessMachine  implements java.io.Serializable {


     private short dpmId;
     private String name;
     private String ip;

    public DataProcessMachine() {
    }

	
    public DataProcessMachine(short dpmId) {
        this.dpmId = dpmId;
    }
    public DataProcessMachine(short dpmId, String name, String ip) {
       this.dpmId = dpmId;
       this.name = name;
       this.ip = ip;
    }
   
    public short getDpmId() {
        return this.dpmId;
    }
    
    public void setDpmId(short dpmId) {
        this.dpmId = dpmId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }




}


