package com.gwac.model;
// Generated 2014-9-1 13:05:37 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Environment generated by hbm2java
 */
@Entity
@Table(name="environment"
    ,schema="public"
)
public class Environment  implements java.io.Serializable {


     private long envId;
     private Float cloudPercent;
     private Date date;
     private Float humidity;
     private Float seeing;
     private Float temperature;
     private Date time;
     private String wather;
     private Float windSpeed;

    public Environment() {
    }

	
    public Environment(long envId) {
        this.envId = envId;
    }
    public Environment(long envId, Float cloudPercent, Date date, Float humidity, Float seeing, Float temperature, Date time, String wather, Float windSpeed) {
       this.envId = envId;
       this.cloudPercent = cloudPercent;
       this.date = date;
       this.humidity = humidity;
       this.seeing = seeing;
       this.temperature = temperature;
       this.time = time;
       this.wather = wather;
       this.windSpeed = windSpeed;
    }
   
     @Id 

    
    @Column(name="env_id", unique=true, nullable=false)
    public long getEnvId() {
        return this.envId;
    }
    
    public void setEnvId(long envId) {
        this.envId = envId;
    }

    
    @Column(name="cloud_percent", precision=8, scale=8)
    public Float getCloudPercent() {
        return this.cloudPercent;
    }
    
    public void setCloudPercent(Float cloudPercent) {
        this.cloudPercent = cloudPercent;
    }

//    @Temporal(TemporalType.DATE)
    @Column(name="date", length=13)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="humidity", precision=8, scale=8)
    public Float getHumidity() {
        return this.humidity;
    }
    
    public void setHumidity(Float humidity) {
        this.humidity = humidity;
    }

    
    @Column(name="seeing", precision=8, scale=8)
    public Float getSeeing() {
        return this.seeing;
    }
    
    public void setSeeing(Float seeing) {
        this.seeing = seeing;
    }

    
    @Column(name="temperature", precision=8, scale=8)
    public Float getTemperature() {
        return this.temperature;
    }
    
    public void setTemperature(Float temperature) {
        this.temperature = temperature;
    }

//    @Temporal(TemporalType.TIME)
    @Column(name="time", length=15)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }

    
    @Column(name="wather", length=64)
    public String getWather() {
        return this.wather;
    }
    
    public void setWather(String wather) {
        this.wather = wather;
    }

    
    @Column(name="wind_speed", precision=8, scale=8)
    public Float getWindSpeed() {
        return this.windSpeed;
    }
    
    public void setWindSpeed(Float windSpeed) {
        this.windSpeed = windSpeed;
    }




}


