package com.gwac.model;
// Generated 2017-1-10 20:46:20 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FileNumber generated by hbm2java
 */
@Entity
@Table(name="file_number"
    ,schema="public"
)
public class FileNumber  implements java.io.Serializable {


     private long fnId;
     private Integer gridId;
     private Integer fieldId;
     private Integer camId;
     private Integer dateStr;
     private Integer ffNumber;

    public FileNumber() {
    }

	
    public FileNumber(long fnId) {
        this.fnId = fnId;
    }
    public FileNumber(long fnId, Integer gridId, Integer fieldId, Integer camId, Integer dateStr, Integer ffNumber) {
       this.fnId = fnId;
       this.gridId = gridId;
       this.fieldId = fieldId;
       this.camId = camId;
       this.dateStr = dateStr;
       this.ffNumber = ffNumber;
    }
   
     @Id 

    
    @Column(name="fn_id", unique=true, nullable=false)
    public long getFnId() {
        return this.fnId;
    }
    
    public void setFnId(long fnId) {
        this.fnId = fnId;
    }

    
    @Column(name="grid_id")
    public Integer getGridId() {
        return this.gridId;
    }
    
    public void setGridId(Integer gridId) {
        this.gridId = gridId;
    }

    
    @Column(name="field_id")
    public Integer getFieldId() {
        return this.fieldId;
    }
    
    public void setFieldId(Integer fieldId) {
        this.fieldId = fieldId;
    }

    
    @Column(name="cam_id")
    public Integer getCamId() {
        return this.camId;
    }
    
    public void setCamId(Integer camId) {
        this.camId = camId;
    }

    
    @Column(name="date_Str")
    public Integer getDateStr() {
        return this.dateStr;
    }
    
    public void setDateStr(Integer dateStr) {
        this.dateStr = dateStr;
    }

    
    @Column(name="ff_number")
    public Integer getFfNumber() {
        return this.ffNumber;
    }
    
    public void setFfNumber(Integer ffNumber) {
        this.ffNumber = ffNumber;
    }




}


