package com.gwac.model;
// Generated Aug 24, 2014 9:21:15 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FitsFileCut generated by hbm2java
 */
@Entity
@Table(name="fits_file_cut"
    ,schema="public"
)
public class FitsFileCut  implements java.io.Serializable {


     private long ffcId;
     private Long starId;
     private Short dpmId;
     private String storePath;
     private String fileName;
     private Long ffId;
     private Long templateFfcId;
     private Boolean isTemplateCut;
     private Long otId;
     private Integer number;

    public FitsFileCut() {
    }

	
    public FitsFileCut(long ffcId) {
        this.ffcId = ffcId;
    }
    public FitsFileCut(long ffcId, Long starId, Short dpmId, String storePath, String fileName, Long ffId, Long templateFfcId, Boolean isTemplateCut, Long otId, Integer number) {
       this.ffcId = ffcId;
       this.starId = starId;
       this.dpmId = dpmId;
       this.storePath = storePath;
       this.fileName = fileName;
       this.ffId = ffId;
       this.templateFfcId = templateFfcId;
       this.isTemplateCut = isTemplateCut;
       this.otId = otId;
       this.number = number;
    }
   
     @Id 
    
    @Column(name="ffc_id", unique=true, nullable=false)
    public long getFfcId() {
        return this.ffcId;
    }
    
    public void setFfcId(long ffcId) {
        this.ffcId = ffcId;
    }
    
    @Column(name="star_id")
    public Long getStarId() {
        return this.starId;
    }
    
    public void setStarId(Long starId) {
        this.starId = starId;
    }
    
    @Column(name="dpm_id")
    public Short getDpmId() {
        return this.dpmId;
    }
    
    public void setDpmId(Short dpmId) {
        this.dpmId = dpmId;
    }
    
    @Column(name="store_path")
    public String getStorePath() {
        return this.storePath;
    }
    
    public void setStorePath(String storePath) {
        this.storePath = storePath;
    }
    
    @Column(name="file_name")
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="ff_id")
    public Long getFfId() {
        return this.ffId;
    }
    
    public void setFfId(Long ffId) {
        this.ffId = ffId;
    }
    
    @Column(name="template_ffc_id")
    public Long getTemplateFfcId() {
        return this.templateFfcId;
    }
    
    public void setTemplateFfcId(Long templateFfcId) {
        this.templateFfcId = templateFfcId;
    }
    
    @Column(name="is_template_cut")
    public Boolean getIsTemplateCut() {
        return this.isTemplateCut;
    }
    
    public void setIsTemplateCut(Boolean isTemplateCut) {
        this.isTemplateCut = isTemplateCut;
    }
    
    @Column(name="ot_id")
    public Long getOtId() {
        return this.otId;
    }
    
    public void setOtId(Long otId) {
        this.otId = otId;
    }
    
    @Column(name="number")
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }




}


