package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FitsFileCutHis generated by hbm2java
 */
@Entity
@Table(name="fits_file_cut_his"
    ,schema="public"
)
public class FitsFileCutHis  implements java.io.Serializable {


     private long ffcId;
     private Long starId;
     private Short dpmId;
     private String storePath;
     private String fileName;
     private Long ffId;
     private Long templateFfcId;
     private Boolean isTemplateCut;
     private Long otId;
     private Integer number;
     private Boolean requestCut;
     private Boolean successCut;
     private Float imgX;
     private Float imgY;
     private Boolean isMissed;

    public FitsFileCutHis() {
    }

	
    public FitsFileCutHis(long ffcId) {
        this.ffcId = ffcId;
    }
    public FitsFileCutHis(long ffcId, Long starId, Short dpmId, String storePath, String fileName, Long ffId, Long templateFfcId, Boolean isTemplateCut, Long otId, Integer number, Boolean requestCut, Boolean successCut, Float imgX, Float imgY, Boolean isMissed) {
       this.ffcId = ffcId;
       this.starId = starId;
       this.dpmId = dpmId;
       this.storePath = storePath;
       this.fileName = fileName;
       this.ffId = ffId;
       this.templateFfcId = templateFfcId;
       this.isTemplateCut = isTemplateCut;
       this.otId = otId;
       this.number = number;
       this.requestCut = requestCut;
       this.successCut = successCut;
       this.imgX = imgX;
       this.imgY = imgY;
       this.isMissed = isMissed;
    }
   
     @Id 

    
    @Column(name="ffc_id", unique=true, nullable=false)
    public long getFfcId() {
        return this.ffcId;
    }
    
    public void setFfcId(long ffcId) {
        this.ffcId = ffcId;
    }

    
    @Column(name="star_id")
    public Long getStarId() {
        return this.starId;
    }
    
    public void setStarId(Long starId) {
        this.starId = starId;
    }

    
    @Column(name="dpm_id")
    public Short getDpmId() {
        return this.dpmId;
    }
    
    public void setDpmId(Short dpmId) {
        this.dpmId = dpmId;
    }

    
    @Column(name="store_path")
    public String getStorePath() {
        return this.storePath;
    }
    
    public void setStorePath(String storePath) {
        this.storePath = storePath;
    }

    
    @Column(name="file_name")
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="ff_id")
    public Long getFfId() {
        return this.ffId;
    }
    
    public void setFfId(Long ffId) {
        this.ffId = ffId;
    }

    
    @Column(name="template_ffc_id")
    public Long getTemplateFfcId() {
        return this.templateFfcId;
    }
    
    public void setTemplateFfcId(Long templateFfcId) {
        this.templateFfcId = templateFfcId;
    }

    
    @Column(name="is_template_cut")
    public Boolean getIsTemplateCut() {
        return this.isTemplateCut;
    }
    
    public void setIsTemplateCut(Boolean isTemplateCut) {
        this.isTemplateCut = isTemplateCut;
    }

    
    @Column(name="ot_id")
    public Long getOtId() {
        return this.otId;
    }
    
    public void setOtId(Long otId) {
        this.otId = otId;
    }

    
    @Column(name="number")
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }

    
    @Column(name="request_cut")
    public Boolean getRequestCut() {
        return this.requestCut;
    }
    
    public void setRequestCut(Boolean requestCut) {
        this.requestCut = requestCut;
    }

    
    @Column(name="success_cut")
    public Boolean getSuccessCut() {
        return this.successCut;
    }
    
    public void setSuccessCut(Boolean successCut) {
        this.successCut = successCut;
    }

    
    @Column(name="img_x", precision=8, scale=8)
    public Float getImgX() {
        return this.imgX;
    }
    
    public void setImgX(Float imgX) {
        this.imgX = imgX;
    }

    
    @Column(name="img_y", precision=8, scale=8)
    public Float getImgY() {
        return this.imgY;
    }
    
    public void setImgY(Float imgY) {
        this.imgY = imgY;
    }

    
    @Column(name="is_missed")
    public Boolean getIsMissed() {
        return this.isMissed;
    }
    
    public void setIsMissed(Boolean isMissed) {
        this.isMissed = isMissed;
    }




}


