package com.gwac.model;
// Generated May 5, 2014 8:56:32 PM by Hibernate Tools 3.2.2.GA



/**
 * FitsFileCut generated by hbm2java
 */
public class FitsFileCut  implements java.io.Serializable {


     private long ffcId;
     private Long starId;
     private Short dpmId;
     private String storePath;
     private String fileName;
     private Long ffId;
     private Long templateFfcId;
     private Boolean isTemplateCut;

    public FitsFileCut() {
    }

	
    public FitsFileCut(long ffcId) {
        this.ffcId = ffcId;
    }
    public FitsFileCut(long ffcId, Long starId, Short dpmId, String storePath, String fileName, Long ffId, Long templateFfcId, Boolean isTemplateCut) {
       this.ffcId = ffcId;
       this.starId = starId;
       this.dpmId = dpmId;
       this.storePath = storePath;
       this.fileName = fileName;
       this.ffId = ffId;
       this.templateFfcId = templateFfcId;
       this.isTemplateCut = isTemplateCut;
    }
   
    public long getFfcId() {
        return this.ffcId;
    }
    
    public void setFfcId(long ffcId) {
        this.ffcId = ffcId;
    }
    public Long getStarId() {
        return this.starId;
    }
    
    public void setStarId(Long starId) {
        this.starId = starId;
    }
    public Short getDpmId() {
        return this.dpmId;
    }
    
    public void setDpmId(Short dpmId) {
        this.dpmId = dpmId;
    }
    public String getStorePath() {
        return this.storePath;
    }
    
    public void setStorePath(String storePath) {
        this.storePath = storePath;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Long getFfId() {
        return this.ffId;
    }
    
    public void setFfId(Long ffId) {
        this.ffId = ffId;
    }
    public Long getTemplateFfcId() {
        return this.templateFfcId;
    }
    
    public void setTemplateFfcId(Long templateFfcId) {
        this.templateFfcId = templateFfcId;
    }
    public Boolean getIsTemplateCut() {
        return this.isTemplateCut;
    }
    
    public void setIsTemplateCut(Boolean isTemplateCut) {
        this.isTemplateCut = isTemplateCut;
    }




}


