package com.gwac.model;
// Generated 2014-9-1 13:05:37 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FitsFile generated by hbm2java
 */
@Entity
@Table(name="fits_file"
    ,schema="public"
)
public class FitsFile  implements java.io.Serializable {


     private long ffId;
     private Short dpmId;
     private Float fieldHeight;
     private Float fieldWidth;
     private String fileName;
     private Float gmbDec;
     private Short gmbId;
     private Float gmbRa;
     private Boolean isTemplate;
     private Float pixelResolution;
     private Long slfId;
     private String storePath;
     private Long templateFfId;
     private Float tspDec;
     private Short tspId;
     private Float tspRa;

    public FitsFile() {
    }

    public FitsFile(Short dpmId, Float fieldHeight, Float fieldWidth, String fileName, Float gmbDec, Short gmbId, Float gmbRa, Boolean isTemplate, Float pixelResolution, Long slfId, String storePath, Long templateFfId, Float tspDec, Short tspId, Float tspRa) {
       this.dpmId = dpmId;
       this.fieldHeight = fieldHeight;
       this.fieldWidth = fieldWidth;
       this.fileName = fileName;
       this.gmbDec = gmbDec;
       this.gmbId = gmbId;
       this.gmbRa = gmbRa;
       this.isTemplate = isTemplate;
       this.pixelResolution = pixelResolution;
       this.slfId = slfId;
       this.storePath = storePath;
       this.templateFfId = templateFfId;
       this.tspDec = tspDec;
       this.tspId = tspId;
       this.tspRa = tspRa;
    }
   
     @GenericGenerator(name="generator", strategy="seqhilo", parameters={@Parameter(name="max_lo", value="49"), @Parameter(name="sequence", value="ff_id_seq")})@Id @GeneratedValue(generator="generator")

    
    @Column(name="ff_id", unique=true, nullable=false)
    public long getFfId() {
        return this.ffId;
    }
    
    public void setFfId(long ffId) {
        this.ffId = ffId;
    }

    
    @Column(name="dpm_id")
    public Short getDpmId() {
        return this.dpmId;
    }
    
    public void setDpmId(Short dpmId) {
        this.dpmId = dpmId;
    }

    
    @Column(name="field_height", precision=8, scale=8)
    public Float getFieldHeight() {
        return this.fieldHeight;
    }
    
    public void setFieldHeight(Float fieldHeight) {
        this.fieldHeight = fieldHeight;
    }

    
    @Column(name="field_width", precision=8, scale=8)
    public Float getFieldWidth() {
        return this.fieldWidth;
    }
    
    public void setFieldWidth(Float fieldWidth) {
        this.fieldWidth = fieldWidth;
    }

    
    @Column(name="file_name")
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="gmb_dec", precision=8, scale=8)
    public Float getGmbDec() {
        return this.gmbDec;
    }
    
    public void setGmbDec(Float gmbDec) {
        this.gmbDec = gmbDec;
    }

    
    @Column(name="gmb_id")
    public Short getGmbId() {
        return this.gmbId;
    }
    
    public void setGmbId(Short gmbId) {
        this.gmbId = gmbId;
    }

    
    @Column(name="gmb_ra", precision=8, scale=8)
    public Float getGmbRa() {
        return this.gmbRa;
    }
    
    public void setGmbRa(Float gmbRa) {
        this.gmbRa = gmbRa;
    }

    
    @Column(name="is_template")
    public Boolean getIsTemplate() {
        return this.isTemplate;
    }
    
    public void setIsTemplate(Boolean isTemplate) {
        this.isTemplate = isTemplate;
    }

    
    @Column(name="pixel_resolution", precision=8, scale=8)
    public Float getPixelResolution() {
        return this.pixelResolution;
    }
    
    public void setPixelResolution(Float pixelResolution) {
        this.pixelResolution = pixelResolution;
    }

    
    @Column(name="slf_id")
    public Long getSlfId() {
        return this.slfId;
    }
    
    public void setSlfId(Long slfId) {
        this.slfId = slfId;
    }

    
    @Column(name="store_path")
    public String getStorePath() {
        return this.storePath;
    }
    
    public void setStorePath(String storePath) {
        this.storePath = storePath;
    }

    
    @Column(name="template_ff_id")
    public Long getTemplateFfId() {
        return this.templateFfId;
    }
    
    public void setTemplateFfId(Long templateFfId) {
        this.templateFfId = templateFfId;
    }

    
    @Column(name="tsp_dec", precision=8, scale=8)
    public Float getTspDec() {
        return this.tspDec;
    }
    
    public void setTspDec(Float tspDec) {
        this.tspDec = tspDec;
    }

    
    @Column(name="tsp_id")
    public Short getTspId() {
        return this.tspId;
    }
    
    public void setTspId(Short tspId) {
        this.tspId = tspId;
    }

    
    @Column(name="tsp_ra", precision=8, scale=8)
    public Float getTspRa() {
        return this.tspRa;
    }
    
    public void setTspRa(Float tspRa) {
        this.tspRa = tspRa;
    }




}


