package com.gwac.model;
// Generated Feb 14, 2014 3:32:17 PM by Hibernate Tools 3.2.2.GA



/**
 * FitsFileCut generated by hbm2java
 */
public class FitsFileCut  implements java.io.Serializable {


     private long ffcId;
     private Long starId;
     private Long dpmId;
     private String storePath;
     private String fileName;

    public FitsFileCut() {
    }

	
    public FitsFileCut(long ffcId) {
        this.ffcId = ffcId;
    }
    public FitsFileCut(long ffcId, Long starId, Long dpmId, String storePath, String fileName) {
       this.ffcId = ffcId;
       this.starId = starId;
       this.dpmId = dpmId;
       this.storePath = storePath;
       this.fileName = fileName;
    }
   
    public long getFfcId() {
        return this.ffcId;
    }
    
    public void setFfcId(long ffcId) {
        this.ffcId = ffcId;
    }
    public Long getStarId() {
        return this.starId;
    }
    
    public void setStarId(Long starId) {
        this.starId = starId;
    }
    public Long getDpmId() {
        return this.dpmId;
    }
    
    public void setDpmId(Long dpmId) {
        this.dpmId = dpmId;
    }
    public String getStorePath() {
        return this.storePath;
    }
    
    public void setStorePath(String storePath) {
        this.storePath = storePath;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }




}


