package com.gwac.model;
// Generated Feb 14, 2014 3:32:17 PM by Hibernate Tools 3.2.2.GA



/**
 * FitsFile generated by hbm2java
 */
public class FitsFile  implements java.io.Serializable {


     private long ffId;
     private Long dpmId;
     private String storePath;
     private String fileName;
     private Long gmbId;
     private Long tspId;

    public FitsFile() {
    }

	
    public FitsFile(long ffId) {
        this.ffId = ffId;
    }
    public FitsFile(long ffId, Long dpmId, String storePath, String fileName, Long gmbId, Long tspId) {
       this.ffId = ffId;
       this.dpmId = dpmId;
       this.storePath = storePath;
       this.fileName = fileName;
       this.gmbId = gmbId;
       this.tspId = tspId;
    }
   
    public long getFfId() {
        return this.ffId;
    }
    
    public void setFfId(long ffId) {
        this.ffId = ffId;
    }
    public Long getDpmId() {
        return this.dpmId;
    }
    
    public void setDpmId(Long dpmId) {
        this.dpmId = dpmId;
    }
    public String getStorePath() {
        return this.storePath;
    }
    
    public void setStorePath(String storePath) {
        this.storePath = storePath;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Long getGmbId() {
        return this.gmbId;
    }
    
    public void setGmbId(Long gmbId) {
        this.gmbId = gmbId;
    }
    public Long getTspId() {
        return this.tspId;
    }
    
    public void setTspId(Long tspId) {
        this.tspId = tspId;
    }




}


