package com.gwac.model;
// Generated Aug 24, 2014 3:05:01 PM by Hibernate Tools 3.2.2.GA



/**
 * FitsFile generated by hbm2java
 */
public class FitsFile  implements java.io.Serializable {


     private long ffId;
     private Short dpmId;
     private String storePath;
     private String fileName;
     private Short gmbId;
     private Float gmbRa;
     private Float gmbDec;
     private Short tspId;
     private Float tspRa;
     private Float tspDec;
     private Float fieldWidth;
     private Float fieldHeight;
     private Float pixelResolution;
     private Long templateFfId;
     private Long slfId;
     private Boolean isTemplate;

    public FitsFile() {
    }

	
    public FitsFile(long ffId) {
        this.ffId = ffId;
    }
    public FitsFile(long ffId, Short dpmId, String storePath, String fileName, Short gmbId, Float gmbRa, Float gmbDec, Short tspId, Float tspRa, Float tspDec, Float fieldWidth, Float fieldHeight, Float pixelResolution, Long templateFfId, Long slfId, Boolean isTemplate) {
       this.ffId = ffId;
       this.dpmId = dpmId;
       this.storePath = storePath;
       this.fileName = fileName;
       this.gmbId = gmbId;
       this.gmbRa = gmbRa;
       this.gmbDec = gmbDec;
       this.tspId = tspId;
       this.tspRa = tspRa;
       this.tspDec = tspDec;
       this.fieldWidth = fieldWidth;
       this.fieldHeight = fieldHeight;
       this.pixelResolution = pixelResolution;
       this.templateFfId = templateFfId;
       this.slfId = slfId;
       this.isTemplate = isTemplate;
    }
   
    public long getFfId() {
        return this.ffId;
    }
    
    public void setFfId(long ffId) {
        this.ffId = ffId;
    }
    public Short getDpmId() {
        return this.dpmId;
    }
    
    public void setDpmId(Short dpmId) {
        this.dpmId = dpmId;
    }
    public String getStorePath() {
        return this.storePath;
    }
    
    public void setStorePath(String storePath) {
        this.storePath = storePath;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    public Short getGmbId() {
        return this.gmbId;
    }
    
    public void setGmbId(Short gmbId) {
        this.gmbId = gmbId;
    }
    public Float getGmbRa() {
        return this.gmbRa;
    }
    
    public void setGmbRa(Float gmbRa) {
        this.gmbRa = gmbRa;
    }
    public Float getGmbDec() {
        return this.gmbDec;
    }
    
    public void setGmbDec(Float gmbDec) {
        this.gmbDec = gmbDec;
    }
    public Short getTspId() {
        return this.tspId;
    }
    
    public void setTspId(Short tspId) {
        this.tspId = tspId;
    }
    public Float getTspRa() {
        return this.tspRa;
    }
    
    public void setTspRa(Float tspRa) {
        this.tspRa = tspRa;
    }
    public Float getTspDec() {
        return this.tspDec;
    }
    
    public void setTspDec(Float tspDec) {
        this.tspDec = tspDec;
    }
    public Float getFieldWidth() {
        return this.fieldWidth;
    }
    
    public void setFieldWidth(Float fieldWidth) {
        this.fieldWidth = fieldWidth;
    }
    public Float getFieldHeight() {
        return this.fieldHeight;
    }
    
    public void setFieldHeight(Float fieldHeight) {
        this.fieldHeight = fieldHeight;
    }
    public Float getPixelResolution() {
        return this.pixelResolution;
    }
    
    public void setPixelResolution(Float pixelResolution) {
        this.pixelResolution = pixelResolution;
    }
    public Long getTemplateFfId() {
        return this.templateFfId;
    }
    
    public void setTemplateFfId(Long templateFfId) {
        this.templateFfId = templateFfId;
    }
    public Long getSlfId() {
        return this.slfId;
    }
    
    public void setSlfId(Long slfId) {
        this.slfId = slfId;
    }
    public Boolean getIsTemplate() {
        return this.isTemplate;
    }
    
    public void setIsTemplate(Boolean isTemplate) {
        this.isTemplate = isTemplate;
    }




}


