package com.gwac.model;
// Generated 2015-10-19 21:58:46 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FollowUpObservation generated by hbm2java
 */
@Entity
@Table(name="follow_up_observation"
    ,schema="public"
)
public class FollowUpObservation  implements java.io.Serializable {


     private long foId;
     private String foName;
     private Long otId;
     private Integer userId;
     private Float ra;
     private Float dec;
     private String epoch;
     private String imageType;
     private Short exposeDuration;
     private Short frameCount;
     private String filter;
     private Short priority;
     private Date triggerTime;
     private Integer backImageCount;
     private String foParmFile;
     private Short foObjCount;
     private String triggerType;

    public FollowUpObservation() {
    }

	
    public FollowUpObservation(long foId) {
        this.foId = foId;
    }
    public FollowUpObservation(long foId, String foName, Long otId, Integer userId, Float ra, Float dec, String epoch, String imageType, Short exposeDuration, Short frameCount, String filter, Short priority, Date triggerTime, Integer backImageCount, String foParmFile, Short foObjCount, String triggerType) {
       this.foId = foId;
       this.foName = foName;
       this.otId = otId;
       this.userId = userId;
       this.ra = ra;
       this.dec = dec;
       this.epoch = epoch;
       this.imageType = imageType;
       this.exposeDuration = exposeDuration;
       this.frameCount = frameCount;
       this.filter = filter;
       this.priority = priority;
       this.triggerTime = triggerTime;
       this.backImageCount = backImageCount;
       this.foParmFile = foParmFile;
       this.foObjCount = foObjCount;
       this.triggerType = triggerType;
    }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "fo_id_seq")})
     @Id 
  @GeneratedValue(generator = "generator")
    @Column(name="fo_id", unique=true, nullable=false)
    public long getFoId() {
        return this.foId;
    }
    
    public void setFoId(long foId) {
        this.foId = foId;
    }

    
    @Column(name="fo_name", length=20)
    public String getFoName() {
        return this.foName;
    }
    
    public void setFoName(String foName) {
        this.foName = foName;
    }

    
    @Column(name="ot_id")
    public Long getOtId() {
        return this.otId;
    }
    
    public void setOtId(Long otId) {
        this.otId = otId;
    }

    
    @Column(name="user_id")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="ra", precision=8, scale=8)
    public Float getRa() {
        return this.ra;
    }
    
    public void setRa(Float ra) {
        this.ra = ra;
    }

    
    @Column(name="dec", precision=8, scale=8)
    public Float getDec() {
        return this.dec;
    }
    
    public void setDec(Float dec) {
        this.dec = dec;
    }

    
    @Column(name="epoch", length=10)
    public String getEpoch() {
        return this.epoch;
    }
    
    public void setEpoch(String epoch) {
        this.epoch = epoch;
    }

    
    @Column(name="image_type", length=10)
    public String getImageType() {
        return this.imageType;
    }
    
    public void setImageType(String imageType) {
        this.imageType = imageType;
    }

    
    @Column(name="expose_duration")
    public Short getExposeDuration() {
        return this.exposeDuration;
    }
    
    public void setExposeDuration(Short exposeDuration) {
        this.exposeDuration = exposeDuration;
    }

    
    @Column(name="frame_count")
    public Short getFrameCount() {
        return this.frameCount;
    }
    
    public void setFrameCount(Short frameCount) {
        this.frameCount = frameCount;
    }

    
    @Column(name="filter")
    public String getFilter() {
        return this.filter;
    }
    
    public void setFilter(String filter) {
        this.filter = filter;
    }

    
    @Column(name="priority")
    public Short getPriority() {
        return this.priority;
    }
    
    public void setPriority(Short priority) {
        this.priority = priority;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="trigger_time", length=29)
    public Date getTriggerTime() {
        return this.triggerTime;
    }
    
    public void setTriggerTime(Date triggerTime) {
        this.triggerTime = triggerTime;
    }

    
    @Column(name="back_image_count")
    public Integer getBackImageCount() {
        return this.backImageCount;
    }
    
    public void setBackImageCount(Integer backImageCount) {
        this.backImageCount = backImageCount;
    }

    
    @Column(name="fo_parm_file")
    public String getFoParmFile() {
        return this.foParmFile;
    }
    
    public void setFoParmFile(String foParmFile) {
        this.foParmFile = foParmFile;
    }

    
    @Column(name="fo_obj_count")
    public Short getFoObjCount() {
        return this.foObjCount;
    }
    
    public void setFoObjCount(Short foObjCount) {
        this.foObjCount = foObjCount;
    }

    
    @Column(name="trigger_type", length=10)
    public String getTriggerType() {
        return this.triggerType;
    }
    
    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType;
    }




}


