package com.gwac.model;
// Generated 2015-10-19 21:58:46 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FollowUpRecord generated by hbm2java
 */
@Entity
@Table(name = "follow_up_record", schema = "public"
)
public class FollowUpRecord implements java.io.Serializable {

  private long frId;
  private Long foId;
  private Short frObjId;
  private Date dateUtc;
  private Float ra;
  private Float dec;
  private Float x;
  private Float y;
  private Float magCalUsno;
  private Float magErr;
  private Float ellipticity;
  private Float classStar;
  private Float fwhm;
  private Short flag;
  private Float b2;
  private Float r2;
  private Float i;
  private Short fuoTypeId;
  private Long fufId;
  private String filter;
  private Integer fuSerialNumber;
  private Long fuoId;

  public FollowUpRecord() {
  }

  public FollowUpRecord(long frId) {
    this.frId = frId;
  }

  public FollowUpRecord(long frId, Long foId, Short frObjId, Date dateUtc, Float ra, Float dec, Float x, Float y, Float magCalUsno, Float magErr, Float ellipticity, Float classStar, Float fwhm, Short flag, Float b2, Float r2, Float i, Short fuoTypeId, Long fufId, String filter) {
    this.frId = frId;
    this.foId = foId;
    this.frObjId = frObjId;
    this.dateUtc = dateUtc;
    this.ra = ra;
    this.dec = dec;
    this.x = x;
    this.y = y;
    this.magCalUsno = magCalUsno;
    this.magErr = magErr;
    this.ellipticity = ellipticity;
    this.classStar = classStar;
    this.fwhm = fwhm;
    this.flag = flag;
    this.b2 = b2;
    this.r2 = r2;
    this.i = i;
    this.fuoTypeId = fuoTypeId;
    this.fufId = fufId;
    this.filter = filter;
  }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "fr_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "fr_id", unique = true, nullable = false)
  public long getFrId() {
    return this.frId;
  }

  public void setFrId(long frId) {
    this.frId = frId;
  }

  @Column(name = "fo_id")
  public Long getFoId() {
    return this.foId;
  }

  public void setFoId(Long foId) {
    this.foId = foId;
  }

  @Column(name = "date_utc", length = 29)
  public Date getDateUtc() {
    return this.dateUtc;
  }

  public void setDateUtc(Date dateUtc) {
    this.dateUtc = dateUtc;
  }

  @Column(name = "ra", precision = 8, scale = 8)
  public Float getRa() {
    return this.ra;
  }

  public void setRa(Float ra) {
    this.ra = ra;
  }

  @Column(name = "dec", precision = 8, scale = 8)
  public Float getDec() {
    return this.dec;
  }

  public void setDec(Float dec) {
    this.dec = dec;
  }

  @Column(name = "x", precision = 8, scale = 8)
  public Float getX() {
    return this.x;
  }

  public void setX(Float x) {
    this.x = x;
  }

  @Column(name = "y", precision = 8, scale = 8)
  public Float getY() {
    return this.y;
  }

  public void setY(Float y) {
    this.y = y;
  }

  @Column(name = "mag_cal_usno", precision = 8, scale = 8)
  public Float getMagCalUsno() {
    return this.magCalUsno;
  }

  public void setMagCalUsno(Float magCalUsno) {
    this.magCalUsno = magCalUsno;
  }

  @Column(name = "mag_err", precision = 8, scale = 8)
  public Float getMagErr() {
    return this.magErr;
  }

  public void setMagErr(Float magErr) {
    this.magErr = magErr;
  }

  @Column(name = "ellipticity", precision = 8, scale = 8)
  public Float getEllipticity() {
    return this.ellipticity;
  }

  public void setEllipticity(Float ellipticity) {
    this.ellipticity = ellipticity;
  }

  @Column(name = "class_star", precision = 8, scale = 8)
  public Float getClassStar() {
    return this.classStar;
  }

  public void setClassStar(Float classStar) {
    this.classStar = classStar;
  }

  @Column(name = "fwhm", precision = 8, scale = 8)
  public Float getFwhm() {
    return this.fwhm;
  }

  public void setFwhm(Float fwhm) {
    this.fwhm = fwhm;
  }

  @Column(name = "flag")
  public Short getFlag() {
    return this.flag;
  }

  public void setFlag(Short flag) {
    this.flag = flag;
  }

  @Column(name = "b2", precision = 8, scale = 8)
  public Float getB2() {
    return this.b2;
  }

  public void setB2(Float b2) {
    this.b2 = b2;
  }

  @Column(name = "r2", precision = 8, scale = 8)
  public Float getR2() {
    return this.r2;
  }

  public void setR2(Float r2) {
    this.r2 = r2;
  }

  @Column(name = "i", precision = 8, scale = 8)
  public Float getI() {
    return this.i;
  }

  public void setI(Float i) {
    this.i = i;
  }

  @Column(name = "filter")
  public String getFilter() {
    return this.filter;
  }

  public void setFilter(String filter) {
    this.filter = filter;
  }

  /**
   * @return the fufId
   */
  @Column(name = "fuf_id")
  public Long getFufId() {
    return fufId;
  }

  /**
   * @param fufId the ufuId to set
   */
  public void setFufId(Long fufId) {
    this.fufId = fufId;
  }

  /**
   * @return the frObjId
   */
  @Column(name = "fr_obj_id")
  public Short getFrObjId() {
    return frObjId;
  }

  /**
   * @param frObjId the frObjId to set
   */
  public void setFrObjId(Short frObjId) {
    this.frObjId = frObjId;
  }

  /**
   * @return the fuSerialNumber 
   */
  @Column(name = "fu_serial_number")
  public Integer getFuSerialNumber() {
    return fuSerialNumber;
  }

  /**
   * @param fuSerialNumber the fuSerialNumber to set
   */
  public void setFuSerialNumber(Integer fuSerialNumber) {
    this.fuSerialNumber = fuSerialNumber;
  }

  /**
   * @return the fuoTypeId
   */
  @Column(name = "fuo_type_id")
  public Short getFuoTypeId() {
    return fuoTypeId;
  }

  /**
   * @param fuoTypeId the fuoTypeId to set
   */
  public void setFuoTypeId(Short fuoTypeId) {
    this.fuoTypeId = fuoTypeId;
  }

  /**
   * @return the fuoId
   */
  @Column(name = "fuo_id")
  public Long getFuoId() {
    return fuoId;
  }

  /**
   * @param fuoId the fuoId to set
   */
  public void setFuoId(Long fuoId) {
    this.fuoId = fuoId;
  }

}
