package com.gwac.model;
// Generated 2015-10-19 21:58:46 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FollowUpRecord generated by hbm2java
 */
@Entity
@Table(name="follow_up_record"
    ,schema="public"
)
public class FollowUpRecord  implements java.io.Serializable {


     private long frId;
     private Long foId;
     private Short frObjNum;
     private Date dateUtc;
     private Float ra;
     private Float dec;
     private Float x;
     private Float y;
     private Float magCalUsno;
     private Float magErr;
     private Float ellipticity;
     private Float classStar;
     private Float fwhm;
     private Short flag;
     private Float b2;
     private Float r2;
     private Float i;
     private String otType;
     private Long ffId;
     private Character filter;

    public FollowUpRecord() {
    }

	
    public FollowUpRecord(long frId) {
        this.frId = frId;
    }
    public FollowUpRecord(long frId, Long foId, Short frObjNum, Date dateUtc, Float ra, Float dec, Float x, Float y, Float magCalUsno, Float magErr, Float ellipticity, Float classStar, Float fwhm, Short flag, Float b2, Float r2, Float i, String otType, Long ffId, Character filter) {
       this.frId = frId;
       this.foId = foId;
       this.frObjNum = frObjNum;
       this.dateUtc = dateUtc;
       this.ra = ra;
       this.dec = dec;
       this.x = x;
       this.y = y;
       this.magCalUsno = magCalUsno;
       this.magErr = magErr;
       this.ellipticity = ellipticity;
       this.classStar = classStar;
       this.fwhm = fwhm;
       this.flag = flag;
       this.b2 = b2;
       this.r2 = r2;
       this.i = i;
       this.otType = otType;
       this.ffId = ffId;
       this.filter = filter;
    }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "fr_id_seq")})
     @Id 
  @GeneratedValue(generator = "generator")
    @Column(name="fr_id", unique=true, nullable=false)
    public long getFrId() {
        return this.frId;
    }
    
    public void setFrId(long frId) {
        this.frId = frId;
    }

    
    @Column(name="fo_id")
    public Long getFoId() {
        return this.foId;
    }
    
    public void setFoId(Long foId) {
        this.foId = foId;
    }

    
    @Column(name="fr_obj_num")
    public Short getFrObjNum() {
        return this.frObjNum;
    }
    
    public void setFrObjNum(Short frObjNum) {
        this.frObjNum = frObjNum;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_utc", length=29)
    public Date getDateUtc() {
        return this.dateUtc;
    }
    
    public void setDateUtc(Date dateUtc) {
        this.dateUtc = dateUtc;
    }

    
    @Column(name="ra", precision=8, scale=8)
    public Float getRa() {
        return this.ra;
    }
    
    public void setRa(Float ra) {
        this.ra = ra;
    }

    
    @Column(name="dec", precision=8, scale=8)
    public Float getDec() {
        return this.dec;
    }
    
    public void setDec(Float dec) {
        this.dec = dec;
    }

    
    @Column(name="x", precision=8, scale=8)
    public Float getX() {
        return this.x;
    }
    
    public void setX(Float x) {
        this.x = x;
    }

    
    @Column(name="y", precision=8, scale=8)
    public Float getY() {
        return this.y;
    }
    
    public void setY(Float y) {
        this.y = y;
    }

    
    @Column(name="mag_cal_usno", precision=8, scale=8)
    public Float getMagCalUsno() {
        return this.magCalUsno;
    }
    
    public void setMagCalUsno(Float magCalUsno) {
        this.magCalUsno = magCalUsno;
    }

    
    @Column(name="mag_err", precision=8, scale=8)
    public Float getMagErr() {
        return this.magErr;
    }
    
    public void setMagErr(Float magErr) {
        this.magErr = magErr;
    }

    
    @Column(name="ellipticity", precision=8, scale=8)
    public Float getEllipticity() {
        return this.ellipticity;
    }
    
    public void setEllipticity(Float ellipticity) {
        this.ellipticity = ellipticity;
    }

    
    @Column(name="class_star", precision=8, scale=8)
    public Float getClassStar() {
        return this.classStar;
    }
    
    public void setClassStar(Float classStar) {
        this.classStar = classStar;
    }

    
    @Column(name="fwhm", precision=8, scale=8)
    public Float getFwhm() {
        return this.fwhm;
    }
    
    public void setFwhm(Float fwhm) {
        this.fwhm = fwhm;
    }

    
    @Column(name="flag")
    public Short getFlag() {
        return this.flag;
    }
    
    public void setFlag(Short flag) {
        this.flag = flag;
    }

    
    @Column(name="b2", precision=8, scale=8)
    public Float getB2() {
        return this.b2;
    }
    
    public void setB2(Float b2) {
        this.b2 = b2;
    }

    
    @Column(name="r2", precision=8, scale=8)
    public Float getR2() {
        return this.r2;
    }
    
    public void setR2(Float r2) {
        this.r2 = r2;
    }

    
    @Column(name="i", precision=8, scale=8)
    public Float getI() {
        return this.i;
    }
    
    public void setI(Float i) {
        this.i = i;
    }

    
    @Column(name="ot_type", length=20)
    public String getOtType() {
        return this.otType;
    }
    
    public void setOtType(String otType) {
        this.otType = otType;
    }

    
    @Column(name="ff_id")
    public Long getFfId() {
        return this.ffId;
    }
    
    public void setFfId(Long ffId) {
        this.ffId = ffId;
    }

    
    @Column(name="filter", length=1)
    public Character getFilter() {
        return this.filter;
    }
    
    public void setFilter(Character filter) {
        this.filter = filter;
    }




}


