package com.gwac.model;
// Generated Feb 14, 2014 3:32:17 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Gimbal generated by hbm2java
 */
public class Gimbal  implements java.io.Serializable {


     private long gmbId;
     private String name;
     private BigDecimal ra;
     private BigDecimal dec;

    public Gimbal() {
    }

	
    public Gimbal(long gmbId) {
        this.gmbId = gmbId;
    }
    public Gimbal(long gmbId, String name, BigDecimal ra, BigDecimal dec) {
       this.gmbId = gmbId;
       this.name = name;
       this.ra = ra;
       this.dec = dec;
    }
   
    public long getGmbId() {
        return this.gmbId;
    }
    
    public void setGmbId(long gmbId) {
        this.gmbId = gmbId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getRa() {
        return this.ra;
    }
    
    public void setRa(BigDecimal ra) {
        this.ra = ra;
    }
    public BigDecimal getDec() {
        return this.dec;
    }
    
    public void setDec(BigDecimal dec) {
        this.dec = dec;
    }




}


