package com.gwac.model;
// Generated 2014-8-30 13:00:35 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gimbal generated by hbm2java
 */
@Entity
@Table(name="gimbal"
    ,schema="public"
)
public class Gimbal  implements java.io.Serializable {


     private short gmbId;
     private String name;
     private Float ra;
     private Float dec;

    public Gimbal() {
    }

	
    public Gimbal(short gmbId) {
        this.gmbId = gmbId;
    }
    public Gimbal(short gmbId, String name, Float ra, Float dec) {
       this.gmbId = gmbId;
       this.name = name;
       this.ra = ra;
       this.dec = dec;
    }
   
     @Id 

    
    @Column(name="gmb_id", unique=true, nullable=false)
    public short getGmbId() {
        return this.gmbId;
    }
    
    public void setGmbId(short gmbId) {
        this.gmbId = gmbId;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ra", precision=8, scale=8)
    public Float getRa() {
        return this.ra;
    }
    
    public void setRa(Float ra) {
        this.ra = ra;
    }

    
    @Column(name="dec", precision=8, scale=8)
    public Float getDec() {
        return this.dec;
    }
    
    public void setDec(Float dec) {
        this.dec = dec;
    }




}


