package com.gwac.model;
// Generated 2014-3-2 17:07:19 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * Grb generated by hbm2java
 */
public class Grb  implements java.io.Serializable {


     private long grbId;
     private String grbName;
     private Date triggerTime;
     private String triggerType;
     private String triggerName;
     private BigDecimal triggerRa;
     private BigDecimal triggerDec;

    public Grb() {
    }

	
    public Grb(long grbId) {
        this.grbId = grbId;
    }
    public Grb(long grbId, String grbName, Date triggerTime, String triggerType, String triggerName, BigDecimal triggerRa, BigDecimal triggerDec) {
       this.grbId = grbId;
       this.grbName = grbName;
       this.triggerTime = triggerTime;
       this.triggerType = triggerType;
       this.triggerName = triggerName;
       this.triggerRa = triggerRa;
       this.triggerDec = triggerDec;
    }
   
    public long getGrbId() {
        return this.grbId;
    }
    
    public void setGrbId(long grbId) {
        this.grbId = grbId;
    }
    public String getGrbName() {
        return this.grbName;
    }
    
    public void setGrbName(String grbName) {
        this.grbName = grbName;
    }
    public Date getTriggerTime() {
        return this.triggerTime;
    }
    
    public void setTriggerTime(Date triggerTime) {
        this.triggerTime = triggerTime;
    }
    public String getTriggerType() {
        return this.triggerType;
    }
    
    public void setTriggerType(String triggerType) {
        this.triggerType = triggerType;
    }
    public String getTriggerName() {
        return this.triggerName;
    }
    
    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }
    public BigDecimal getTriggerRa() {
        return this.triggerRa;
    }
    
    public void setTriggerRa(BigDecimal triggerRa) {
        this.triggerRa = triggerRa;
    }
    public BigDecimal getTriggerDec() {
        return this.triggerDec;
    }
    
    public void setTriggerDec(BigDecimal triggerDec) {
        this.triggerDec = triggerDec;
    }




}


