package com.gwac.model;
// Generated 2016-11-24 16:38:56 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MoveObjectRecord generated by hbm2java
 */
@Entity
@Table(name="move_object_record"
    ,schema="public"
)
public class MoveObjectRecord  implements java.io.Serializable {


     private long oorId;
     private Float speedX;
     private Float speedY;
     private Float speedGreatCircle;
     private Long movId;

    public MoveObjectRecord() {
    }

	
    public MoveObjectRecord(long oorId) {
        this.oorId = oorId;
    }
    public MoveObjectRecord(long oorId, Float speedX, Float speedY, Float speedGreatCircle, Long movId) {
       this.oorId = oorId;
       this.speedX = speedX;
       this.speedY = speedY;
       this.speedGreatCircle = speedGreatCircle;
       this.movId = movId;
    }
   
     @Id 

    
    @Column(name="oor_id", unique=true, nullable=false)
    public long getOorId() {
        return this.oorId;
    }
    
    public void setOorId(long oorId) {
        this.oorId = oorId;
    }

    
    @Column(name="speed_x", precision=8, scale=8)
    public Float getSpeedX() {
        return this.speedX;
    }
    
    public void setSpeedX(Float speedX) {
        this.speedX = speedX;
    }

    
    @Column(name="speed_y", precision=8, scale=8)
    public Float getSpeedY() {
        return this.speedY;
    }
    
    public void setSpeedY(Float speedY) {
        this.speedY = speedY;
    }

    
    @Column(name="speed_great_circle", precision=8, scale=8)
    public Float getSpeedGreatCircle() {
        return this.speedGreatCircle;
    }
    
    public void setSpeedGreatCircle(Float speedGreatCircle) {
        this.speedGreatCircle = speedGreatCircle;
    }

    
    @Column(name="mov_id")
    public Long getMovId() {
        return this.movId;
    }
    
    public void setMovId(Long movId) {
        this.movId = movId;
    }




}


