package com.gwac.model;
// Generated 2016-11-24 16:38:56 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * MoveObject generated by hbm2java
 */
@Entity
@Table(name = "move_object", schema = "public"
)
public class MoveObject implements java.io.Serializable {

  private long movId;
  private Short firstFrameNum;
  private Short lastFrameNum;
  private Date firstFrameTime;
  private Date lastFrameTime;
  private Float minSpeed;
  private Float maxSpeed;
  private Float meanSpeed;
  private Float speedSigma;
  private Short totalFrameNumber;
  private Float avgFramePointNumber;
  private String comment;
  private Character movType;
  private String dateStr;
  private Integer skyId;
  private Integer dpmId;

  public MoveObject() {
  }

  public MoveObject(long movId) {
    this.movId = movId;
  }

  public MoveObject(long movId, Short firstFrameNum, Short lastFrameNum, Date firstFrameTime, Date lastFrameTime, Float minSpeed, Float maxSpeed, Float meanSpeed, Float speedSigma, Short totalFrameNumber, Float avgFramePointNumber, String comment, Character movType, String dateStr, Integer skyId, Integer dpmId) {
    this.movId = movId;
    this.firstFrameNum = firstFrameNum;
    this.lastFrameNum = lastFrameNum;
    this.firstFrameTime = firstFrameTime;
    this.lastFrameTime = lastFrameTime;
    this.minSpeed = minSpeed;
    this.maxSpeed = maxSpeed;
    this.meanSpeed = meanSpeed;
    this.speedSigma = speedSigma;
    this.totalFrameNumber = totalFrameNumber;
    this.avgFramePointNumber = avgFramePointNumber;
    this.comment = comment;
    this.movType = movType;
    this.dateStr = dateStr;
    this.skyId = skyId;
    this.dpmId = dpmId;
  }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "ot_leve2_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "mov_id", unique = true, nullable = false)
  public long getMovId() {
    return this.movId;
  }

  public void setMovId(long movId) {
    this.movId = movId;
  }

  @Column(name = "first_frame_num")
  public Short getFirstFrameNum() {
    return this.firstFrameNum;
  }

  public void setFirstFrameNum(Short firstFrameNum) {
    this.firstFrameNum = firstFrameNum;
  }

  @Column(name = "last_frame_num")
  public Short getLastFrameNum() {
    return this.lastFrameNum;
  }

  public void setLastFrameNum(Short lastFrameNum) {
    this.lastFrameNum = lastFrameNum;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "first_frame_time", length = 29)
  public Date getFirstFrameTime() {
    return this.firstFrameTime;
  }

  public void setFirstFrameTime(Date firstFrameTime) {
    this.firstFrameTime = firstFrameTime;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "last_frame_time", length = 29)
  public Date getLastFrameTime() {
    return this.lastFrameTime;
  }

  public void setLastFrameTime(Date lastFrameTime) {
    this.lastFrameTime = lastFrameTime;
  }

  @Column(name = "min_speed", precision = 8, scale = 8)
  public Float getMinSpeed() {
    return this.minSpeed;
  }

  public void setMinSpeed(Float minSpeed) {
    this.minSpeed = minSpeed;
  }

  @Column(name = "max_speed", precision = 8, scale = 8)
  public Float getMaxSpeed() {
    return this.maxSpeed;
  }

  public void setMaxSpeed(Float maxSpeed) {
    this.maxSpeed = maxSpeed;
  }

  @Column(name = "mean_speed", precision = 8, scale = 8)
  public Float getMeanSpeed() {
    return this.meanSpeed;
  }

  public void setMeanSpeed(Float meanSpeed) {
    this.meanSpeed = meanSpeed;
  }

  @Column(name = "speed_sigma", precision = 8, scale = 8)
  public Float getSpeedSigma() {
    return this.speedSigma;
  }

  public void setSpeedSigma(Float speedSigma) {
    this.speedSigma = speedSigma;
  }

  @Column(name = "total_frame_number")
  public Short getTotalFrameNumber() {
    return this.totalFrameNumber;
  }

  public void setTotalFrameNumber(Short totalFrameNumber) {
    this.totalFrameNumber = totalFrameNumber;
  }

  @Column(name = "avg_frame_point_number")
  public Float getAvgFramePointNumber() {
    return this.avgFramePointNumber;
  }

  public void setAvgFramePointNumber(Float avgFramePointNumber) {
    this.avgFramePointNumber = avgFramePointNumber;
  }

  @Column(name = "comment")
  public String getComment() {
    return this.comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  @Column(name = "mov_type", length = 1)
  public Character getMovType() {
    return this.movType;
  }

  public void setMovType(Character movType) {
    this.movType = movType;
  }

  @Column(name = "date_str", length = 6)
  public String getDateStr() {
    return this.dateStr;
  }

  public void setDateStr(String dateStr) {
    this.dateStr = dateStr;
  }

  @Column(name = "sky_id")
  public Integer getSkyId() {
    return this.skyId;
  }

  public void setSkyId(Integer skyId) {
    this.skyId = skyId;
  }

  @Column(name = "dpm_id")
  public Integer getDpmId() {
    return this.dpmId;
  }

  public void setDpmId(Integer dpmId) {
    this.dpmId = dpmId;
  }

}
