package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ConfigFile generated by hbm2java
 */
@Entity
@Table(name = "multimedia_resource", schema = "public"
)
public class MultimediaResource implements java.io.Serializable {

  private long mrId;
  private String enName;
  private String chName;
  private String path;
  private char type;
  private String comment;

  public MultimediaResource() {
  }

  public MultimediaResource(long mrId) {
    this.mrId = mrId;
  }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "mr_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "mr_id", unique = true, nullable = false)
  public long getMrId() {
    return this.mrId;
  }

  public void setMrId(long mrId) {
    this.mrId = mrId;
  }

  /**
   * @return the enName
   */
  @Column(name = "en_name")
  public String getEnName() {
    return enName;
  }

  /**
   * @param enName the enName to set
   */
  public void setEnName(String enName) {
    this.enName = enName;
  }

  /**
   * @return the chName
   */
  @Column(name = "ch_name")
  public String getChName() {
    return chName;
  }

  /**
   * @param chName the chName to set
   */
  public void setChName(String chName) {
    this.chName = chName;
  }

  /**
   * @return the path
   */
  @Column(name = "path")
  public String getPath() {
    return path;
  }

  /**
   * @param path the path to set
   */
  public void setPath(String path) {
    this.path = path;
  }

  /**
   * @return the type
   */
  @Column(name = "type")
  public char getType() {
    return type;
  }

  /**
   * @param type the type to set
   */
  public void setType(char type) {
    this.type = type;
  }

  /**
   * @return the comment
   */
  @Column(name = "comment")
  public String getComment() {
    return comment;
  }

  /**
   * @param comment the comment to set
   */
  public void setComment(String comment) {
    this.comment = comment;
  }

}
