package com.gwac.model;
// Generated 2017-1-10 20:46:20 by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ObjectRelation generated by hbm2java
 */
@Entity
@Table(name="object_relation"
    ,schema="public"
)
public class ObjectRelation  implements java.io.Serializable {


     private ObjectRelationId id;

    public ObjectRelation() {
    }

    public ObjectRelation(ObjectRelationId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="parentObjId", column=@Column(name="parent_obj_id") ), 
        @AttributeOverride(name="childObjId", column=@Column(name="child_obj_id") ) } )
    public ObjectRelationId getId() {
        return this.id;
    }
    
    public void setId(ObjectRelationId id) {
        this.id = id;
    }




}


