package com.gwac.model;
// Generated 2017-1-10 20:46:20 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ObjectType generated by hbm2java
 */
@Entity
@Table(name="object_type"
    ,schema="public"
)
public class ObjectType  implements java.io.Serializable {


     private int objTypeId;
     private String objTypeName;
     private String objTypeNameEn;
     private String objCfgTmplFile;
     private String comment;
     private String objTypeNameCh;

    public ObjectType() {
    }

	
    public ObjectType(int objTypeId) {
        this.objTypeId = objTypeId;
    }
    public ObjectType(int objTypeId, String objTypeName, String objTypeNameEn, String objCfgTmplFile, String comment, String objTypeNameCh) {
       this.objTypeId = objTypeId;
       this.objTypeName = objTypeName;
       this.objTypeNameEn = objTypeNameEn;
       this.objCfgTmplFile = objCfgTmplFile;
       this.comment = comment;
       this.objTypeNameCh = objTypeNameCh;
    }
   
     @Id 

    
    @Column(name="obj_type_id", unique=true, nullable=false)
    public int getObjTypeId() {
        return this.objTypeId;
    }
    
    public void setObjTypeId(int objTypeId) {
        this.objTypeId = objTypeId;
    }

    
    @Column(name="obj_type_name", length=128)
    public String getObjTypeName() {
        return this.objTypeName;
    }
    
    public void setObjTypeName(String objTypeName) {
        this.objTypeName = objTypeName;
    }

    
    @Column(name="obj_type_name_en", length=128)
    public String getObjTypeNameEn() {
        return this.objTypeNameEn;
    }
    
    public void setObjTypeNameEn(String objTypeNameEn) {
        this.objTypeNameEn = objTypeNameEn;
    }

    
    @Column(name="obj_cfg_tmpl_file", length=256)
    public String getObjCfgTmplFile() {
        return this.objCfgTmplFile;
    }
    
    public void setObjCfgTmplFile(String objCfgTmplFile) {
        this.objCfgTmplFile = objCfgTmplFile;
    }

    
    @Column(name="comment", length=1024)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="obj_type_name_ch", length=128)
    public String getObjTypeNameCh() {
        return this.objTypeNameCh;
    }
    
    public void setObjTypeNameCh(String objTypeNameCh) {
        this.objTypeNameCh = objTypeNameCh;
    }




}


