package com.gwac.model;
// Generated 2017-1-10 20:46:20 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ObservationSite generated by hbm2java
 */
@Entity
@Table(name="observation_site"
    ,schema="public"
)
public class ObservationSite  implements java.io.Serializable {


     private int obsSiteId;
     private String obsSiteName;
     private Float obsSiteLgtd;
     private Float obsSiteLatd;
     private Float obsSiteAltd;
     private String comment;

    public ObservationSite() {
    }

	
    public ObservationSite(int obsSiteId) {
        this.obsSiteId = obsSiteId;
    }
    public ObservationSite(int obsSiteId, String obsSiteName, Float obsSiteLgtd, Float obsSiteLatd, Float obsSiteAltd, String comment) {
       this.obsSiteId = obsSiteId;
       this.obsSiteName = obsSiteName;
       this.obsSiteLgtd = obsSiteLgtd;
       this.obsSiteLatd = obsSiteLatd;
       this.obsSiteAltd = obsSiteAltd;
       this.comment = comment;
    }
   
     @Id 

    
    @Column(name="obs_site_id", unique=true, nullable=false)
    public int getObsSiteId() {
        return this.obsSiteId;
    }
    
    public void setObsSiteId(int obsSiteId) {
        this.obsSiteId = obsSiteId;
    }

    
    @Column(name="obs_site _name", length=128)
    public String getObsSiteName() {
        return this.obsSiteName;
    }
    
    public void setObsSiteName(String obsSiteName) {
        this.obsSiteName = obsSiteName;
    }

    
    @Column(name="obs_site_lgtd", precision=8, scale=8)
    public Float getObsSiteLgtd() {
        return this.obsSiteLgtd;
    }
    
    public void setObsSiteLgtd(Float obsSiteLgtd) {
        this.obsSiteLgtd = obsSiteLgtd;
    }

    
    @Column(name="obs_site_latd", precision=8, scale=8)
    public Float getObsSiteLatd() {
        return this.obsSiteLatd;
    }
    
    public void setObsSiteLatd(Float obsSiteLatd) {
        this.obsSiteLatd = obsSiteLatd;
    }

    
    @Column(name="obs_site_altd", precision=8, scale=8)
    public Float getObsSiteAltd() {
        return this.obsSiteAltd;
    }
    
    public void setObsSiteAltd(Float obsSiteAltd) {
        this.obsSiteAltd = obsSiteAltd;
    }

    
    @Column(name="comment", length=1024)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }




}


