package com.gwac.model;
// Generated May 4, 2014 10:28:46 AM by Hibernate Tools 3.2.2.GA



/**
 * OtBase generated by hbm2java
 */
public class OtBase  implements java.io.Serializable {


     private long otId;
     private String name;
     private Float ra;
     private Float dec;

    public OtBase() {
    }

	
    public OtBase(long otId) {
        this.otId = otId;
    }
    public OtBase(long otId, String name, Float ra, Float dec) {
       this.otId = otId;
       this.name = name;
       this.ra = ra;
       this.dec = dec;
    }
   
    public long getOtId() {
        return this.otId;
    }
    
    public void setOtId(long otId) {
        this.otId = otId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Float getRa() {
        return this.ra;
    }
    
    public void setRa(Float ra) {
        this.ra = ra;
    }
    public Float getDec() {
        return this.dec;
    }
    
    public void setDec(Float dec) {
        this.dec = dec;
    }




}


