package com.gwac.model;
// Generated May 5, 2014 8:56:32 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * OtBase generated by hbm2java
 */
public class OtBase  implements java.io.Serializable {


     private long otId;
     private String name;
     private Float ra;
     private Float dec;
     private Date foundTimeUtc;

    public OtBase() {
    }

	
    public OtBase(long otId) {
        this.otId = otId;
    }
    public OtBase(long otId, String name, Float ra, Float dec, Date foundTimeUtc) {
       this.otId = otId;
       this.name = name;
       this.ra = ra;
       this.dec = dec;
       this.foundTimeUtc = foundTimeUtc;
    }
   
    public long getOtId() {
        return this.otId;
    }
    
    public void setOtId(long otId) {
        this.otId = otId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Float getRa() {
        return this.ra;
    }
    
    public void setRa(Float ra) {
        this.ra = ra;
    }
    public Float getDec() {
        return this.dec;
    }
    
    public void setDec(Float dec) {
        this.dec = dec;
    }
    public Date getFoundTimeUtc() {
        return this.foundTimeUtc;
    }
    
    public void setFoundTimeUtc(Date foundTimeUtc) {
        this.foundTimeUtc = foundTimeUtc;
    }




}


