package com.gwac.model;
// Generated 2014-9-1 13:05:37 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtLevel3 generated by hbm2java
 */
@Entity
@Table(name="ot_level3"
    ,schema="public"
)
public class OtLevel3  implements java.io.Serializable {


     private long otId;
     private String comments;
     private Float dec;
     private String dpmName;
     private Date foundTimeUtc;
     private String identify;
     private Boolean isRecognize;
     private Integer lastFfNumber;
     private Short maxSuccOccurTimes;
     private String name;
     private Short otType;
     private Float ra;
     private Short succOccurTimes;
     private Integer total;
     private Float xtemp;
     private Float ytemp;

    public OtLevel3() {
    }

	
    public OtLevel3(long otId) {
        this.otId = otId;
    }
    public OtLevel3(long otId, String comments, Float dec, String dpmName, Date foundTimeUtc, String identify, Boolean isRecognize, Integer lastFfNumber, Short maxSuccOccurTimes, String name, Short otType, Float ra, Short succOccurTimes, Integer total, Float xtemp, Float ytemp) {
       this.otId = otId;
       this.comments = comments;
       this.dec = dec;
       this.dpmName = dpmName;
       this.foundTimeUtc = foundTimeUtc;
       this.identify = identify;
       this.isRecognize = isRecognize;
       this.lastFfNumber = lastFfNumber;
       this.maxSuccOccurTimes = maxSuccOccurTimes;
       this.name = name;
       this.otType = otType;
       this.ra = ra;
       this.succOccurTimes = succOccurTimes;
       this.total = total;
       this.xtemp = xtemp;
       this.ytemp = ytemp;
    }
   
     @Id 

    
    @Column(name="ot_id", unique=true, nullable=false)
    public long getOtId() {
        return this.otId;
    }
    
    public void setOtId(long otId) {
        this.otId = otId;
    }

    
    @Column(name="comments", length=1024)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="dec", precision=8, scale=8)
    public Float getDec() {
        return this.dec;
    }
    
    public void setDec(Float dec) {
        this.dec = dec;
    }

    
    @Column(name="dpm_name", length=3)
    public String getDpmName() {
        return this.dpmName;
    }
    
    public void setDpmName(String dpmName) {
        this.dpmName = dpmName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="found_time_utc", length=29)
    public Date getFoundTimeUtc() {
        return this.foundTimeUtc;
    }
    
    public void setFoundTimeUtc(Date foundTimeUtc) {
        this.foundTimeUtc = foundTimeUtc;
    }

    
    @Column(name="identify", length=21)
    public String getIdentify() {
        return this.identify;
    }
    
    public void setIdentify(String identify) {
        this.identify = identify;
    }

    
    @Column(name="is_recognize")
    public Boolean getIsRecognize() {
        return this.isRecognize;
    }
    
    public void setIsRecognize(Boolean isRecognize) {
        this.isRecognize = isRecognize;
    }

    
    @Column(name="last_ff_number")
    public Integer getLastFfNumber() {
        return this.lastFfNumber;
    }
    
    public void setLastFfNumber(Integer lastFfNumber) {
        this.lastFfNumber = lastFfNumber;
    }

    
    @Column(name="max_succ_occur_times")
    public Short getMaxSuccOccurTimes() {
        return this.maxSuccOccurTimes;
    }
    
    public void setMaxSuccOccurTimes(Short maxSuccOccurTimes) {
        this.maxSuccOccurTimes = maxSuccOccurTimes;
    }

    
    @Column(name="name", length=12)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ot_type")
    public Short getOtType() {
        return this.otType;
    }
    
    public void setOtType(Short otType) {
        this.otType = otType;
    }

    
    @Column(name="ra", precision=8, scale=8)
    public Float getRa() {
        return this.ra;
    }
    
    public void setRa(Float ra) {
        this.ra = ra;
    }

    
    @Column(name="succ_occur_times")
    public Short getSuccOccurTimes() {
        return this.succOccurTimes;
    }
    
    public void setSuccOccurTimes(Short succOccurTimes) {
        this.succOccurTimes = succOccurTimes;
    }

    
    @Column(name="total")
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }

    
    @Column(name="xtemp", precision=8, scale=8)
    public Float getXtemp() {
        return this.xtemp;
    }
    
    public void setXtemp(Float xtemp) {
        this.xtemp = xtemp;
    }

    
    @Column(name="ytemp", precision=8, scale=8)
    public Float getYtemp() {
        return this.ytemp;
    }
    
    public void setYtemp(Float ytemp) {
        this.ytemp = ytemp;
    }




}


