package com.gwac.model;
// Generated Aug 24, 2014 3:05:01 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * OtLevel2His generated by hbm2java
 */
public class OtLevel2His  implements java.io.Serializable {


     private long otId;
     private OtType otType;
     private String name;
     private Float ra;
     private Float dec;
     private Date foundTimeUtc;
     private String identify;
     private Float xtemp;
     private Float ytemp;
     private Integer lastFfNumber;
     private Integer total;
     private Short succOccurTimes;
     private Short maxSuccOccurTimes;
     private Boolean isRecognize;
     private String comments;
     private String dpmName;

    public OtLevel2His() {
    }

	
    public OtLevel2His(long otId) {
        this.otId = otId;
    }
    public OtLevel2His(long otId, OtType otType, String name, Float ra, Float dec, Date foundTimeUtc, String identify, Float xtemp, Float ytemp, Integer lastFfNumber, Integer total, Short succOccurTimes, Short maxSuccOccurTimes, Boolean isRecognize, String comments, String dpmName) {
       this.otId = otId;
       this.otType = otType;
       this.name = name;
       this.ra = ra;
       this.dec = dec;
       this.foundTimeUtc = foundTimeUtc;
       this.identify = identify;
       this.xtemp = xtemp;
       this.ytemp = ytemp;
       this.lastFfNumber = lastFfNumber;
       this.total = total;
       this.succOccurTimes = succOccurTimes;
       this.maxSuccOccurTimes = maxSuccOccurTimes;
       this.isRecognize = isRecognize;
       this.comments = comments;
       this.dpmName = dpmName;
    }
   
    public long getOtId() {
        return this.otId;
    }
    
    public void setOtId(long otId) {
        this.otId = otId;
    }
    public OtType getOtType() {
        return this.otType;
    }
    
    public void setOtType(OtType otType) {
        this.otType = otType;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Float getRa() {
        return this.ra;
    }
    
    public void setRa(Float ra) {
        this.ra = ra;
    }
    public Float getDec() {
        return this.dec;
    }
    
    public void setDec(Float dec) {
        this.dec = dec;
    }
    public Date getFoundTimeUtc() {
        return this.foundTimeUtc;
    }
    
    public void setFoundTimeUtc(Date foundTimeUtc) {
        this.foundTimeUtc = foundTimeUtc;
    }
    public String getIdentify() {
        return this.identify;
    }
    
    public void setIdentify(String identify) {
        this.identify = identify;
    }
    public Float getXtemp() {
        return this.xtemp;
    }
    
    public void setXtemp(Float xtemp) {
        this.xtemp = xtemp;
    }
    public Float getYtemp() {
        return this.ytemp;
    }
    
    public void setYtemp(Float ytemp) {
        this.ytemp = ytemp;
    }
    public Integer getLastFfNumber() {
        return this.lastFfNumber;
    }
    
    public void setLastFfNumber(Integer lastFfNumber) {
        this.lastFfNumber = lastFfNumber;
    }
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }
    public Short getSuccOccurTimes() {
        return this.succOccurTimes;
    }
    
    public void setSuccOccurTimes(Short succOccurTimes) {
        this.succOccurTimes = succOccurTimes;
    }
    public Short getMaxSuccOccurTimes() {
        return this.maxSuccOccurTimes;
    }
    
    public void setMaxSuccOccurTimes(Short maxSuccOccurTimes) {
        this.maxSuccOccurTimes = maxSuccOccurTimes;
    }
    public Boolean getIsRecognize() {
        return this.isRecognize;
    }
    
    public void setIsRecognize(Boolean isRecognize) {
        this.isRecognize = isRecognize;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public String getDpmName() {
        return this.dpmName;
    }
    
    public void setDpmName(String dpmName) {
        this.dpmName = dpmName;
    }




}


