package com.gwac.model;
// Generated Aug 24, 2014 3:05:01 PM by Hibernate Tools 3.2.2.GA



/**
 * OtNumber generated by hbm2java
 */
public class OtNumber  implements java.io.Serializable {


     private long otnId;
     private String date;
     private Integer number;
     private Character otLevel;

    public OtNumber() {
    }

	
    public OtNumber(long otnId) {
        this.otnId = otnId;
    }
    public OtNumber(long otnId, String date, Integer number, Character otLevel) {
       this.otnId = otnId;
       this.date = date;
       this.number = number;
       this.otLevel = otLevel;
    }
   
    public long getOtnId() {
        return this.otnId;
    }
    
    public void setOtnId(long otnId) {
        this.otnId = otnId;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }
    public Character getOtLevel() {
        return this.otLevel;
    }
    
    public void setOtLevel(Character otLevel) {
        this.otLevel = otLevel;
    }




}


