package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * OtNumber generated by hbm2java
 */
@Entity
@Table(name = "ot_number", schema = "public"
)
public class OtNumber implements java.io.Serializable {

  private long otnId;
  private String date;
  private Integer number;
  private Character otLevel;

  public OtNumber() {
  }

  public OtNumber(long otnId) {
    this.otnId = otnId;
  }

  public OtNumber(long otnId, String date, Integer number, Character otLevel) {
    this.otnId = otnId;
    this.date = date;
    this.number = number;
    this.otLevel = otLevel;
  }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "otn_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")

  @Column(name = "otn_id", unique = true, nullable = false)
  public long getOtnId() {
    return this.otnId;
  }

  public void setOtnId(long otnId) {
    this.otnId = otnId;
  }

  @Column(name = "date", length = 32)
  public String getDate() {
    return this.date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  @Column(name = "number")
  public Integer getNumber() {
    return this.number;
  }

  public void setNumber(Integer number) {
    this.number = number;
  }

  @Column(name = "ot_level", length = 1)
  public Character getOtLevel() {
    return this.otLevel;
  }

  public void setOtLevel(Character otLevel) {
    this.otLevel = otLevel;
  }

}
