package com.gwac.model;
// Generated 2014-8-27 21:38:36 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtObserveRecordLevel1 generated by hbm2java
 */
@Entity
@Table(name="ot_observe_record_level1"
    ,schema="public"
)
public class OtObserveRecordLevel1  implements java.io.Serializable {


     private long oorId;
     private Long otId;
     private Long ffId;
     private Long ffcId;
     private Short otTypeId;
     private Float raD;
     private Float decD;
     private Float x;
     private Float y;
     private Float XTemp;
     private Float YTemp;
     private Date dateUt;
     private Float flux;
     private Boolean flag;
     private Float flagChb;
     private Float background;
     private Float threshold;
     private Float magAper;
     private Float magerrAper;
     private Float ellipticity;
     private Short classStar;
     private Boolean otFlag;

    public OtObserveRecordLevel1() {
    }

	
    public OtObserveRecordLevel1(long oorId) {
        this.oorId = oorId;
    }
    public OtObserveRecordLevel1(long oorId, Long otId, Long ffId, Long ffcId, Short otTypeId, Float raD, Float decD, Float x, Float y, Float XTemp, Float YTemp, Date dateUt, Float flux, Boolean flag, Float flagChb, Float background, Float threshold, Float magAper, Float magerrAper, Float ellipticity, Short classStar, Boolean otFlag) {
       this.oorId = oorId;
       this.otId = otId;
       this.ffId = ffId;
       this.ffcId = ffcId;
       this.otTypeId = otTypeId;
       this.raD = raD;
       this.decD = decD;
       this.x = x;
       this.y = y;
       this.XTemp = XTemp;
       this.YTemp = YTemp;
       this.dateUt = dateUt;
       this.flux = flux;
       this.flag = flag;
       this.flagChb = flagChb;
       this.background = background;
       this.threshold = threshold;
       this.magAper = magAper;
       this.magerrAper = magerrAper;
       this.ellipticity = ellipticity;
       this.classStar = classStar;
       this.otFlag = otFlag;
    }
   
     @Id 

    
    @Column(name="oor_id", unique=true, nullable=false)
    public long getOorId() {
        return this.oorId;
    }
    
    public void setOorId(long oorId) {
        this.oorId = oorId;
    }

    
    @Column(name="ot_id")
    public Long getOtId() {
        return this.otId;
    }
    
    public void setOtId(Long otId) {
        this.otId = otId;
    }

    
    @Column(name="ff_id")
    public Long getFfId() {
        return this.ffId;
    }
    
    public void setFfId(Long ffId) {
        this.ffId = ffId;
    }

    
    @Column(name="ffc_id")
    public Long getFfcId() {
        return this.ffcId;
    }
    
    public void setFfcId(Long ffcId) {
        this.ffcId = ffcId;
    }

    
    @Column(name="ot_type_id")
    public Short getOtTypeId() {
        return this.otTypeId;
    }
    
    public void setOtTypeId(Short otTypeId) {
        this.otTypeId = otTypeId;
    }

    
    @Column(name="ra_d", precision=8, scale=8)
    public Float getRaD() {
        return this.raD;
    }
    
    public void setRaD(Float raD) {
        this.raD = raD;
    }

    
    @Column(name="dec_d", precision=8, scale=8)
    public Float getDecD() {
        return this.decD;
    }
    
    public void setDecD(Float decD) {
        this.decD = decD;
    }

    
    @Column(name="x", precision=8, scale=8)
    public Float getX() {
        return this.x;
    }
    
    public void setX(Float x) {
        this.x = x;
    }

    
    @Column(name="y", precision=8, scale=8)
    public Float getY() {
        return this.y;
    }
    
    public void setY(Float y) {
        this.y = y;
    }

    
    @Column(name="x_temp", precision=8, scale=8)
    public Float getXTemp() {
        return this.XTemp;
    }
    
    public void setXTemp(Float XTemp) {
        this.XTemp = XTemp;
    }

    
    @Column(name="y_temp", precision=8, scale=8)
    public Float getYTemp() {
        return this.YTemp;
    }
    
    public void setYTemp(Float YTemp) {
        this.YTemp = YTemp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_ut", length=29)
    public Date getDateUt() {
        return this.dateUt;
    }
    
    public void setDateUt(Date dateUt) {
        this.dateUt = dateUt;
    }

    
    @Column(name="flux", precision=8, scale=8)
    public Float getFlux() {
        return this.flux;
    }
    
    public void setFlux(Float flux) {
        this.flux = flux;
    }

    
    @Column(name="flag")
    public Boolean getFlag() {
        return this.flag;
    }
    
    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

    
    @Column(name="flag_chb", precision=8, scale=8)
    public Float getFlagChb() {
        return this.flagChb;
    }
    
    public void setFlagChb(Float flagChb) {
        this.flagChb = flagChb;
    }

    
    @Column(name="background", precision=8, scale=8)
    public Float getBackground() {
        return this.background;
    }
    
    public void setBackground(Float background) {
        this.background = background;
    }

    
    @Column(name="threshold", precision=8, scale=8)
    public Float getThreshold() {
        return this.threshold;
    }
    
    public void setThreshold(Float threshold) {
        this.threshold = threshold;
    }

    
    @Column(name="mag_aper", precision=8, scale=8)
    public Float getMagAper() {
        return this.magAper;
    }
    
    public void setMagAper(Float magAper) {
        this.magAper = magAper;
    }

    
    @Column(name="magerr_aper", precision=8, scale=8)
    public Float getMagerrAper() {
        return this.magerrAper;
    }
    
    public void setMagerrAper(Float magerrAper) {
        this.magerrAper = magerrAper;
    }

    
    @Column(name="ellipticity", precision=8, scale=8)
    public Float getEllipticity() {
        return this.ellipticity;
    }
    
    public void setEllipticity(Float ellipticity) {
        this.ellipticity = ellipticity;
    }

    
    @Column(name="class_star")
    public Short getClassStar() {
        return this.classStar;
    }
    
    public void setClassStar(Short classStar) {
        this.classStar = classStar;
    }

    
    @Column(name="ot_flag")
    public Boolean getOtFlag() {
        return this.otFlag;
    }
    
    public void setOtFlag(Boolean otFlag) {
        this.otFlag = otFlag;
    }




}


