package com.gwac.model;
// Generated May 4, 2014 10:28:46 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * OtObserveRecord generated by hbm2java
 */
public class OtObserveRecord  implements java.io.Serializable {


     private long oorId;
     private Long otId;
     private Long ffId;
     private Float ra;
     private Float dec;
     private Float x;
     private Float y;
     private Date datetime;
     private Float mag;
     private Float magErr;
     private Float ellipticity;
     private Float signalNoise;
     private Float fwhm;
     private Float flux;
     private Float fluxErr;
     private Long cmpStarId;
     private Long mchStarId;
     private Long ffcId;
     private Short otTypeId;

    public OtObserveRecord() {
    }

	
    public OtObserveRecord(long oorId) {
        this.oorId = oorId;
    }
    public OtObserveRecord(long oorId, Long otId, Long ffId, Float ra, Float dec, Float x, Float y, Date datetime, Float mag, Float magErr, Float ellipticity, Float signalNoise, Float fwhm, Float flux, Float fluxErr, Long cmpStarId, Long mchStarId, Long ffcId, Short otTypeId) {
       this.oorId = oorId;
       this.otId = otId;
       this.ffId = ffId;
       this.ra = ra;
       this.dec = dec;
       this.x = x;
       this.y = y;
       this.datetime = datetime;
       this.mag = mag;
       this.magErr = magErr;
       this.ellipticity = ellipticity;
       this.signalNoise = signalNoise;
       this.fwhm = fwhm;
       this.flux = flux;
       this.fluxErr = fluxErr;
       this.cmpStarId = cmpStarId;
       this.mchStarId = mchStarId;
       this.ffcId = ffcId;
       this.otTypeId = otTypeId;
    }
   
    public long getOorId() {
        return this.oorId;
    }
    
    public void setOorId(long oorId) {
        this.oorId = oorId;
    }
    public Long getOtId() {
        return this.otId;
    }
    
    public void setOtId(Long otId) {
        this.otId = otId;
    }
    public Long getFfId() {
        return this.ffId;
    }
    
    public void setFfId(Long ffId) {
        this.ffId = ffId;
    }
    public Float getRa() {
        return this.ra;
    }
    
    public void setRa(Float ra) {
        this.ra = ra;
    }
    public Float getDec() {
        return this.dec;
    }
    
    public void setDec(Float dec) {
        this.dec = dec;
    }
    public Float getX() {
        return this.x;
    }
    
    public void setX(Float x) {
        this.x = x;
    }
    public Float getY() {
        return this.y;
    }
    
    public void setY(Float y) {
        this.y = y;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public Float getMag() {
        return this.mag;
    }
    
    public void setMag(Float mag) {
        this.mag = mag;
    }
    public Float getMagErr() {
        return this.magErr;
    }
    
    public void setMagErr(Float magErr) {
        this.magErr = magErr;
    }
    public Float getEllipticity() {
        return this.ellipticity;
    }
    
    public void setEllipticity(Float ellipticity) {
        this.ellipticity = ellipticity;
    }
    public Float getSignalNoise() {
        return this.signalNoise;
    }
    
    public void setSignalNoise(Float signalNoise) {
        this.signalNoise = signalNoise;
    }
    public Float getFwhm() {
        return this.fwhm;
    }
    
    public void setFwhm(Float fwhm) {
        this.fwhm = fwhm;
    }
    public Float getFlux() {
        return this.flux;
    }
    
    public void setFlux(Float flux) {
        this.flux = flux;
    }
    public Float getFluxErr() {
        return this.fluxErr;
    }
    
    public void setFluxErr(Float fluxErr) {
        this.fluxErr = fluxErr;
    }
    public Long getCmpStarId() {
        return this.cmpStarId;
    }
    
    public void setCmpStarId(Long cmpStarId) {
        this.cmpStarId = cmpStarId;
    }
    public Long getMchStarId() {
        return this.mchStarId;
    }
    
    public void setMchStarId(Long mchStarId) {
        this.mchStarId = mchStarId;
    }
    public Long getFfcId() {
        return this.ffcId;
    }
    
    public void setFfcId(Long ffcId) {
        this.ffcId = ffcId;
    }
    public Short getOtTypeId() {
        return this.otTypeId;
    }
    
    public void setOtTypeId(Short otTypeId) {
        this.otTypeId = otTypeId;
    }




}


