package com.gwac.model;
// Generated 2016-5-19 10:38:07 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OtTmplWrong generated by hbm2java
 */
@Entity
@Table(name = "ot_tmpl_wrong", schema = "public"
)
public class OtTmplWrong implements java.io.Serializable {

  private long otId;
  private String name;
  private Float ra;
  private Float dec;
  private Float mag;
  private Long healpixId;
  private Character dataProduceMethod;
  private Date firstFoundTimeUtc;
  private Date lastFoundTimeUtc;
  private Integer matchedTotal;
  private Boolean isValid;
  private Short ottId;
  private Character otClass;

  public OtTmplWrong() {
  }

  public OtTmplWrong(long otId) {
    this.otId = otId;
  }

  public OtTmplWrong(long otId, String name, Float ra, Float dec, Float mag, Long healpixId, Character dataProduceMethod, Date firstFoundTimeUtc, Date lastFoundTimeUtc, Integer matchedTotal, Boolean isValid) {
    this.otId = otId;
    this.name = name;
    this.ra = ra;
    this.dec = dec;
    this.mag = mag;
    this.healpixId = healpixId;
    this.dataProduceMethod = dataProduceMethod;
    this.firstFoundTimeUtc = firstFoundTimeUtc;
    this.lastFoundTimeUtc = lastFoundTimeUtc;
    this.matchedTotal = matchedTotal;
    this.isValid = isValid;
  }

  @Id
  @Column(name = "ot_id", unique = true, nullable = false)
  public long getOtId() {
    return this.otId;
  }

  public void setOtId(long otId) {
    this.otId = otId;
  }

  @Column(name = "name", length = 14)
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Column(name = "ra", precision = 8, scale = 8)
  public Float getRa() {
    return this.ra;
  }

  public void setRa(Float ra) {
    this.ra = ra;
  }

  @Column(name = "dec", precision = 8, scale = 8)
  public Float getDec() {
    return this.dec;
  }

  public void setDec(Float dec) {
    this.dec = dec;
  }

  @Column(name = "mag", precision = 8, scale = 8)
  public Float getMag() {
    return this.mag;
  }

  public void setMag(Float mag) {
    this.mag = mag;
  }

  @Column(name = "healpix_id")
  public Long getHealpixId() {
    return this.healpixId;
  }

  public void setHealpixId(Long healpixId) {
    this.healpixId = healpixId;
  }

  @Column(name = "data_produce_method", length = 1)
  public Character getDataProduceMethod() {
    return this.dataProduceMethod;
  }

  public void setDataProduceMethod(Character dataProduceMethod) {
    this.dataProduceMethod = dataProduceMethod;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "first_found_time_utc", length = 29)
  public Date getFirstFoundTimeUtc() {
    return this.firstFoundTimeUtc;
  }

  public void setFirstFoundTimeUtc(Date firstFoundTimeUtc) {
    this.firstFoundTimeUtc = firstFoundTimeUtc;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "last_found_time_utc", length = 29)
  public Date getLastFoundTimeUtc() {
    return this.lastFoundTimeUtc;
  }

  public void setLastFoundTimeUtc(Date lastFoundTimeUtc) {
    this.lastFoundTimeUtc = lastFoundTimeUtc;
  }

  @Column(name = "matched_total")
  public Integer getMatchedTotal() {
    return this.matchedTotal;
  }

  public void setMatchedTotal(Integer matchedTotal) {
    this.matchedTotal = matchedTotal;
  }

  @Column(name = "is_valid")
  public Boolean getIsValid() {
    return this.isValid;
  }

  public void setIsValid(Boolean isValid) {
    this.isValid = isValid;
  }

  /**
   * @return the ottId
   */
  @Column(name = "ott_id")
  public Short getOttId() {
    return ottId;
  }

  /**
   * @param ottId the ottId to set
   */
  public void setOttId(Short ottId) {
    this.ottId = ottId;
  }

  /**
   * @return the otClass
   */
  @Column(name = "ot_class")
  public Character getOtClass() {
    return otClass;
  }

  /**
   * @param otClass the otClass to set
   */
  public void setOtClass(Character otClass) {
    this.otClass = otClass;
  }

}
