package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * OtType generated by hbm2java
 */
@Entity
@Table(name="ot_type"
    ,schema="public"
)
public class OtType  implements java.io.Serializable {


     private short otTypeId;
     private String otTypeName;
     private String otTableName;
     private String comments;

    public OtType() {
    }

	
    public OtType(short otTypeId) {
        this.otTypeId = otTypeId;
    }
    public OtType(short otTypeId, String otTypeName, String otTableName, String comments) {
       this.otTypeId = otTypeId;
       this.otTypeName = otTypeName;
       this.otTableName = otTableName;
       this.comments = comments;
    }
   
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "ot_type_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "ot_type_id", unique = true, nullable = false)
    public short getOtTypeId() {
        return this.otTypeId;
    }
    
    public void setOtTypeId(short otTypeId) {
        this.otTypeId = otTypeId;
    }

    
    @Column(name="ot_type_name")
    public String getOtTypeName() {
        return this.otTypeName;
    }
    
    public void setOtTypeName(String otTypeName) {
        this.otTypeName = otTypeName;
    }

    
    @Column(name="ot_table_name", length=64)
    public String getOtTableName() {
        return this.otTableName;
    }
    
    public void setOtTableName(String otTableName) {
        this.otTableName = otTableName;
    }

    
    @Column(name="comments", length=1024)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


