package com.gwac.model;
// Generated May 5, 2014 8:56:32 PM by Hibernate Tools 3.2.2.GA



/**
 * OtType generated by hbm2java
 */
public class OtType  implements java.io.Serializable {


     private short otTypeId;
     private String otTypeName;
     private String otTableName;

    public OtType() {
    }

	
    public OtType(short otTypeId) {
        this.otTypeId = otTypeId;
    }
    public OtType(short otTypeId, String otTypeName, String otTableName) {
       this.otTypeId = otTypeId;
       this.otTypeName = otTypeName;
       this.otTableName = otTableName;
    }
   
    public short getOtTypeId() {
        return this.otTypeId;
    }
    
    public void setOtTypeId(short otTypeId) {
        this.otTypeId = otTypeId;
    }
    public String getOtTypeName() {
        return this.otTypeName;
    }
    
    public void setOtTypeName(String otTypeName) {
        this.otTypeName = otTypeName;
    }
    public String getOtTableName() {
        return this.otTableName;
    }
    
    public void setOtTableName(String otTableName) {
        this.otTableName = otTableName;
    }




}


