package com.gwac.model;
// Generated 2015-5-7 18:38:58 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ProcessStatus generated by hbm2java
 */
@Entity
@Table(name="process_status"
    ,schema="public"
)
public class ProcessStatus  implements java.io.Serializable {


     private Short psId;
     private String psName;
     private String psComment;

    public ProcessStatus() {
    }

	
    public ProcessStatus(Short psId) {
        this.psId = psId;
    }
    public ProcessStatus(Short psId, String psName, String psComment) {
       this.psId = psId;
       this.psName = psName;
       this.psComment = psComment;
    }
   
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "ps_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
    @Column(name="ps_id", unique=true, nullable=false)
    public Short getPsId() {
        return this.psId;
    }
    
    public void setPsId(Short psId) {
        this.psId = psId;
    }

    
    @Column(name="ps_name")
    public String getPsName() {
        return this.psName;
    }
    
    public void setPsName(String psName) {
        this.psName = psName;
    }

    
    @Column(name="ps_comment")
    public String getPsComment() {
        return this.psComment;
    }
    
    public void setPsComment(String psComment) {
        this.psComment = psComment;
    }




}


