package com.gwac.model;
// Generated 2014-9-1 13:05:37 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StarKnow generated by hbm2java
 */
@Entity
@Table(name="star_know"
    ,schema="public"
)
public class StarKnow  implements java.io.Serializable {


     private long starId;
     private Float dec;
     private Float mag;
     private Float ra;
     private String starName;
     private Short vtId;

    public StarKnow() {
    }

	
    public StarKnow(long starId) {
        this.starId = starId;
    }
    public StarKnow(long starId, Float dec, Float mag, Float ra, String starName, Short vtId) {
       this.starId = starId;
       this.dec = dec;
       this.mag = mag;
       this.ra = ra;
       this.starName = starName;
       this.vtId = vtId;
    }
   
     @Id 

    
    @Column(name="star_id", unique=true, nullable=false)
    public long getStarId() {
        return this.starId;
    }
    
    public void setStarId(long starId) {
        this.starId = starId;
    }

    
    @Column(name="dec", precision=8, scale=8)
    public Float getDec() {
        return this.dec;
    }
    
    public void setDec(Float dec) {
        this.dec = dec;
    }

    
    @Column(name="mag", precision=8, scale=8)
    public Float getMag() {
        return this.mag;
    }
    
    public void setMag(Float mag) {
        this.mag = mag;
    }

    
    @Column(name="ra", precision=8, scale=8)
    public Float getRa() {
        return this.ra;
    }
    
    public void setRa(Float ra) {
        this.ra = ra;
    }

    
    @Column(name="star_name")
    public String getStarName() {
        return this.starName;
    }
    
    public void setStarName(String starName) {
        this.starName = starName;
    }

    
    @Column(name="vt_id")
    public Short getVtId() {
        return this.vtId;
    }
    
    public void setVtId(Short vtId) {
        this.vtId = vtId;
    }




}


