package com.gwac.model;
// Generated May 4, 2014 10:28:46 AM by Hibernate Tools 3.2.2.GA



/**
 * StarKnow generated by hbm2java
 */
public class StarKnow  implements java.io.Serializable {


     private long starId;
     private String starName;
     private Float ra;
     private Float dec;
     private Float mag;
     private Short vtId;

    public StarKnow() {
    }

	
    public StarKnow(long starId) {
        this.starId = starId;
    }
    public StarKnow(long starId, String starName, Float ra, Float dec, Float mag, Short vtId) {
       this.starId = starId;
       this.starName = starName;
       this.ra = ra;
       this.dec = dec;
       this.mag = mag;
       this.vtId = vtId;
    }
   
    public long getStarId() {
        return this.starId;
    }
    
    public void setStarId(long starId) {
        this.starId = starId;
    }
    public String getStarName() {
        return this.starName;
    }
    
    public void setStarName(String starName) {
        this.starName = starName;
    }
    public Float getRa() {
        return this.ra;
    }
    
    public void setRa(Float ra) {
        this.ra = ra;
    }
    public Float getDec() {
        return this.dec;
    }
    
    public void setDec(Float dec) {
        this.dec = dec;
    }
    public Float getMag() {
        return this.mag;
    }
    
    public void setMag(Float mag) {
        this.mag = mag;
    }
    public Short getVtId() {
        return this.vtId;
    }
    
    public void setVtId(Short vtId) {
        this.vtId = vtId;
    }




}


