package com.gwac.model;
// Generated 2014-9-1 13:05:37 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ConfigFile generated by hbm2java
 */
@Entity
@Table(name = "sync_file", schema = "public"
)
public class SyncFile implements java.io.Serializable {

  private long sfId;
  private String fileName;
  private String path;
  private Date storeTime;
  private Boolean isSync;
  private Boolean isSyncSuccess;

  public SyncFile() {
  }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "sf_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "sf_id", unique = true, nullable = false)
  public long getSfId() {
    return sfId;
  }

  /**
   * @param sfId the sfId to set
   */
  public void setSfId(long sfId) {
    this.sfId = sfId;
  }

  /**
   * @return the fileName
   */
  @Column(name = "file_name")
  public String getFileName() {
    return fileName;
  }

  /**
   * @param fileName the fileName to set
   */
  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  /**
   * @return the path
   */
  @Column(name = "path")
  public String getPath() {
    return path;
  }

  /**
   * @param path the path to set
   */
  public void setPath(String path) {
    this.path = path;
  }

  /**
   * @return the storeTime
   */
  @Column(name = "store_time")
  public Date getStoreTime() {
    return storeTime;
  }

  /**
   * @param storeTime the storeTime to set
   */
  public void setStoreTime(Date storeTime) {
    this.storeTime = storeTime;
  }

  /**
   * @return the isSync
   */
  @Column(name = "is_sync")
  public Boolean getIsSync() {
    return isSync;
  }

  /**
   * @param isSync the isSync to set
   */
  public void setIsSync(Boolean isSync) {
    this.isSync = isSync;
  }

  /**
   * @return the isSyncSuccess
   */
  @Column(name = "is_sync_success")
  public Boolean getIsSyncSuccess() {
    return isSyncSuccess;
  }

  /**
   * @param isSyncSuccess the isSyncSuccess to set
   */
  public void setIsSyncSuccess(Boolean isSyncSuccess) {
    this.isSyncSuccess = isSyncSuccess;
  }

}
