package com.gwac.model;
// Generated Aug 25, 2014 8:19:59 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemStatus generated by hbm2java
 */
@Entity
@Table(name="system_status"
    ,schema="public"
)
public class SystemStatus  implements java.io.Serializable {


     private int id;
     private String dateStr6;
     private Float totalStorageSize;
     private Float usedStorageSize;

    public SystemStatus() {
    }

	
    public SystemStatus(int id) {
        this.id = id;
    }
    public SystemStatus(int id, String dateStr6, Float totalStorageSize, Float usedStorageSize) {
       this.id = id;
       this.dateStr6 = dateStr6;
       this.totalStorageSize = totalStorageSize;
       this.usedStorageSize = usedStorageSize;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="date_str6", length=32)
    public String getDateStr6() {
        return this.dateStr6;
    }
    
    public void setDateStr6(String dateStr6) {
        this.dateStr6 = dateStr6;
    }
    
    @Column(name="total_storage_size", precision=8, scale=8)
    public Float getTotalStorageSize() {
        return this.totalStorageSize;
    }
    
    public void setTotalStorageSize(Float totalStorageSize) {
        this.totalStorageSize = totalStorageSize;
    }
    
    @Column(name="used_storage_size", precision=8, scale=8)
    public Float getUsedStorageSize() {
        return this.usedStorageSize;
    }
    
    public void setUsedStorageSize(Float usedStorageSize) {
        this.usedStorageSize = usedStorageSize;
    }




}


