package com.gwac.model;
// Generated 2017-1-10 20:46:20 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FileNumber generated by hbm2java
 */
@Entity
@Table(name = "system_log", schema = "public"
)
public class SystemLog implements java.io.Serializable {

  private long logId;
  private char logType;
  private Integer logCode;
  private Date logDate;
  private String logContent;

  public SystemLog() {
  }

  public SystemLog(long logId) {
    this.logId = logId;
  }


  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "log_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "log_id", unique = true, nullable = false)
  public long getLogId() {
    return this.logId;
  }

  public void setLogId(long logId) {
    this.logId = logId;
  }

  /**
   * @return the logType
   */
  @Column(name = "log_type")
  public char getLogType() {
    return logType;
  }

  /**
   * @param logType the logType to set
   */
  public void setLogType(char logType) {
    this.logType = logType;
  }

  /**
   * @return the logCode
   */
  @Column(name = "log_code")
  public Integer getLogCode() {
    return logCode;
  }

  /**
   * @param logCode the logCode to set
   */
  public void setLogCode(Integer logCode) {
    this.logCode = logCode;
  }

  /**
   * @return the logDate
   */
  @Column(name = "log_date")
  public Date getLogDate() {
    return logDate;
  }

  /**
   * @param logDate the logDate to set
   */
  public void setLogDate(Date logDate) {
    this.logDate = logDate;
  }

  /**
   * @return the logContent
   */
  @Column(name = "log_content")
  public String getLogContent() {
    return logContent;
  }

  /**
   * @param logContent the logContent to set
   */
  public void setLogContent(String logContent) {
    this.logContent = logContent;
  }

}
