package com.gwac.model;
// Generated 2014-3-2 17:07:19 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Telescope generated by hbm2java
 */
public class Telescope  implements java.io.Serializable {


     private short tspId;
     private String name;
     private BigDecimal ra;
     private BigDecimal dec;
     private Short diameter;
     private Float focalRatio;
     private String ccdType;

    public Telescope() {
    }

	
    public Telescope(short tspId) {
        this.tspId = tspId;
    }
    public Telescope(short tspId, String name, BigDecimal ra, BigDecimal dec, Short diameter, Float focalRatio, String ccdType) {
       this.tspId = tspId;
       this.name = name;
       this.ra = ra;
       this.dec = dec;
       this.diameter = diameter;
       this.focalRatio = focalRatio;
       this.ccdType = ccdType;
    }
   
    public short getTspId() {
        return this.tspId;
    }
    
    public void setTspId(short tspId) {
        this.tspId = tspId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getRa() {
        return this.ra;
    }
    
    public void setRa(BigDecimal ra) {
        this.ra = ra;
    }
    public BigDecimal getDec() {
        return this.dec;
    }
    
    public void setDec(BigDecimal dec) {
        this.dec = dec;
    }
    public Short getDiameter() {
        return this.diameter;
    }
    
    public void setDiameter(Short diameter) {
        this.diameter = diameter;
    }
    public Float getFocalRatio() {
        return this.focalRatio;
    }
    
    public void setFocalRatio(Float focalRatio) {
        this.focalRatio = focalRatio;
    }
    public String getCcdType() {
        return this.ccdType;
    }
    
    public void setCcdType(String ccdType) {
        this.ccdType = ccdType;
    }




}


