package com.gwac.model;
// Generated Feb 14, 2014 3:32:17 PM by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Telescope generated by hbm2java
 */
public class Telescope  implements java.io.Serializable {


     private long tspId;
     private String name;
     private BigDecimal ra;
     private BigDecimal dec;

    public Telescope() {
    }

	
    public Telescope(long tspId) {
        this.tspId = tspId;
    }
    public Telescope(long tspId, String name, BigDecimal ra, BigDecimal dec) {
       this.tspId = tspId;
       this.name = name;
       this.ra = ra;
       this.dec = dec;
    }
   
    public long getTspId() {
        return this.tspId;
    }
    
    public void setTspId(long tspId) {
        this.tspId = tspId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getRa() {
        return this.ra;
    }
    
    public void setRa(BigDecimal ra) {
        this.ra = ra;
    }
    public BigDecimal getDec() {
        return this.dec;
    }
    
    public void setDec(BigDecimal dec) {
        this.dec = dec;
    }




}


