package com.gwac.model;
// Generated 2014-3-2 17:07:19 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;

/**
 * Telescope generated by hbm2java
 */
public class Telescope  implements java.io.Serializable {


     private short tspId;
     private String name;
     private Float ra;
     private Float dec;
     private Short diameter;
     private Float focalRatio;
     private String ccdType;

    public Telescope() {
    }

	
    public Telescope(short tspId) {
        this.tspId = tspId;
    }
    public Telescope(short tspId, String name, Float ra, Float dec, Short diameter, Float focalRatio, String ccdType) {
       this.tspId = tspId;
       this.name = name;
       this.ra = ra;
       this.dec = dec;
       this.diameter = diameter;
       this.focalRatio = focalRatio;
       this.ccdType = ccdType;
    }
   
    public short getTspId() {
        return this.tspId;
    }
    
    public void setTspId(short tspId) {
        this.tspId = tspId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Short getDiameter() {
        return this.diameter;
    }
    
    public void setDiameter(Short diameter) {
        this.diameter = diameter;
    }
    public Float getFocalRatio() {
        return this.focalRatio;
    }
    
    public void setFocalRatio(Float focalRatio) {
        this.focalRatio = focalRatio;
    }
    public String getCcdType() {
        return this.ccdType;
    }
    
    public void setCcdType(String ccdType) {
        this.ccdType = ccdType;
    }

  /**
   * @return the ra
   */
  public Float getRa() {
    return ra;
  }

  /**
   * @param ra the ra to set
   */
  public void setRa(Float ra) {
    this.ra = ra;
  }

  /**
   * @return the dec
   */
  public Float getDec() {
    return dec;
  }

  /**
   * @param dec the dec to set
   */
  public void setDec(Float dec) {
    this.dec = dec;
  }




}


