package com.gwac.model;
// Generated 2014-9-1 13:05:37 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UploadFileUnstore generated by hbm2java
 */
@Entity
@Table(name="upload_file_unstore"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="file_name") 
)
public class UploadFileUnstore  implements java.io.Serializable {


     private long ufuId;
     private String fileName;
     private Character fileType;
     private String storePath;
     private Date uploadDate;
     private Boolean uploadSuccess;
     private Date sendTime;
     private Date processDoneTime;

    public UploadFileUnstore() {
    }

    public UploadFileUnstore(String fileName, Character fileType, String storePath, Date uploadDate, Boolean uploadSuccess) {
       this.fileName = fileName;
       this.fileType = fileType;
       this.storePath = storePath;
       this.uploadDate = uploadDate;
       this.uploadSuccess = uploadSuccess;
    }
   
     @GenericGenerator(name="generator", strategy="seqhilo", parameters={@Parameter(name="max_lo", value="49"), @Parameter(name="sequence", value="ufu_id_seq")})@Id @GeneratedValue(generator="generator")

    
    @Column(name="ufu_id", unique=true, nullable=false)
    public long getUfuId() {
        return this.ufuId;
    }
    
    public void setUfuId(long ufuId) {
        this.ufuId = ufuId;
    }

    
    @Column(name="file_name", unique=true)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="file_type", length=1)
    public Character getFileType() {
        return this.fileType;
    }
    
    public void setFileType(Character fileType) {
        this.fileType = fileType;
    }

    
    @Column(name="store_path")
    public String getStorePath() {
        return this.storePath;
    }
    
    public void setStorePath(String storePath) {
        this.storePath = storePath;
    }

//    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="upload_date", length=29)
    public Date getUploadDate() {
        return this.uploadDate;
    }
    
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    
    @Column(name="upload_success")
    public Boolean getUploadSuccess() {
        return this.uploadSuccess;
    }
    
    public void setUploadSuccess(Boolean uploadSuccess) {
        this.uploadSuccess = uploadSuccess;
    }

  /**
   * @return the sendTime
   */
//    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="send_time", length=29)
  public Date getSendTime() {
    return sendTime;
  }

  /**
   * @param sendTime the sendTime to set
   */
  public void setSendTime(Date sendTime) {
    this.sendTime = sendTime;
  }

  /**
   * @return the processDoneTime
   */
//    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="process_done_time", length=29)
  public Date getProcessDoneTime() {
    return processDoneTime;
  }

  /**
   * @param processDoneTime the processDoneTime to set
   */
  public void setProcessDoneTime(Date processDoneTime) {
    this.processDoneTime = processDoneTime;
  }




}


