package com.gwac.model;
// Generated 2015-11-5 20:06:22 by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserAction generated by hbm2java
 */
@Entity
@Table(name="user_action"
    ,schema="public"
)
public class UserAction  implements java.io.Serializable {

     private Integer uaId;
     private String uaName;
     private String uaComment;

    public UserAction() {
    }

    public UserAction(Integer uaId, String uaName, String uaComment) {
       this.uaId = uaId;
       this.uaName = uaName;
       this.uaComment = uaComment;
    }
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "ua_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
    @Column(name="ua_id", unique=true, nullable=false)
    public Integer getUaId() {
        return this.uaId;
    }
    
    public void setUaId(Integer uaId) {
        this.uaId = uaId;
    }


    @Column(name="ua_name", length=24)
    public String getUaName() {
        return this.uaName;
    }
    
    public void setUaName(String uaName) {
        this.uaName = uaName;
    }


    @Column(name="ua_comment", length=1024)
    public String getUaComment() {
        return this.uaComment;
    }
    
    public void setUaComment(String uaComment) {
        this.uaComment = uaComment;
    }



}


