package com.gwac.model;
// Generated 2015-11-5 20:06:22 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name="user_info"
    ,schema="public"
)
public class UserInfo  implements java.io.Serializable {


     private int uiId;
     private String name;
     private String address;
     private Date registerDate;
     private String password;
     private String loginName;
     private String position;
     private String comments;
     private Boolean registerPass;
     private String email;
     private String mobilPhone;

    public UserInfo() {
    }

	
    public UserInfo(int uiId) {
        this.uiId = uiId;
    }
    public UserInfo(int uiId, String name, String address, Date registerDate, String password, String loginName, String position, String comments, Boolean registerPass, String email, String mobilPhone) {
       this.uiId = uiId;
       this.name = name;
       this.address = address;
       this.registerDate = registerDate;
       this.password = password;
       this.loginName = loginName;
       this.position = position;
       this.comments = comments;
       this.registerPass = registerPass;
       this.email = email;
       this.mobilPhone = mobilPhone;
    }
   
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "ui_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
    @Column(name="ui_id", unique=true, nullable=false)
    public int getUiId() {
        return this.uiId;
    }
    
    public void setUiId(int uiId) {
        this.uiId = uiId;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="register_date", length=29)
    public Date getRegisterDate() {
        return this.registerDate;
    }
    
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="login_name")
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    
    @Column(name="position")
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }

    
    @Column(name="comments", length=1024)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="register_pass")
    public Boolean getRegisterPass() {
        return this.registerPass;
    }
    
    public void setRegisterPass(Boolean registerPass) {
        this.registerPass = registerPass;
    }

    
    @Column(name="email", length=32)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="mobil_phone", length=32)
    public String getMobilPhone() {
        return this.mobilPhone;
    }
    
    public void setMobilPhone(String mobilPhone) {
        this.mobilPhone = mobilPhone;
    }




}


