package com.gwac.model;
// Generated May 4, 2014 10:28:46 AM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo  implements java.io.Serializable {


     private int uiId;
     private String name;
     private String address;
     private Date createDate;
     private String password;

    public UserInfo() {
    }

	
    public UserInfo(int uiId) {
        this.uiId = uiId;
    }
    public UserInfo(int uiId, String name, String address, Date createDate, String password) {
       this.uiId = uiId;
       this.name = name;
       this.address = address;
       this.createDate = createDate;
       this.password = password;
    }
   
    public int getUiId() {
        return this.uiId;
    }
    
    public void setUiId(int uiId) {
        this.uiId = uiId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


