package com.gwac.model;
// Generated Dec 23, 2013 8:07:43 PM by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private long userId;
     private String name;
     private String address;
     private Date createdDate;

    public User() {
    }

    public User(long userId, String name, String address, Date createdDate) {
       this.userId = userId;
       this.name = name;
       this.address = address;
       this.createdDate = createdDate;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }




}


