package com.gwac.model;
// Generated 2014-9-1 13:05:37 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name="user_info"
    ,schema="public"
)
public class UserInfo  implements java.io.Serializable {


     private int uiId;
     private String address;
     private Date createDate;
     private String name;
     private String password;

    public UserInfo() {
    }

	
    public UserInfo(int uiId) {
        this.uiId = uiId;
    }
    public UserInfo(int uiId, String address, Date createDate, String name, String password) {
       this.uiId = uiId;
       this.address = address;
       this.createDate = createDate;
       this.name = name;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="ui_id", unique=true, nullable=false)
    public int getUiId() {
        return this.uiId;
    }
    
    public void setUiId(int uiId) {
        this.uiId = uiId;
    }

    
    @Column(name="address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

//    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=29)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


