package com.gwac.model;
// Generated Aug 24, 2014 3:05:01 PM by Hibernate Tools 3.2.2.GA



/**
 * VariationType generated by hbm2java
 */
public class VariationType  implements java.io.Serializable {


     private long vtId;
     private String vtName;

    public VariationType() {
    }

	
    public VariationType(long vtId) {
        this.vtId = vtId;
    }
    public VariationType(long vtId, String vtName) {
       this.vtId = vtId;
       this.vtName = vtName;
    }
   
    public long getVtId() {
        return this.vtId;
    }
    
    public void setVtId(long vtId) {
        this.vtId = vtId;
    }
    public String getVtName() {
        return this.vtName;
    }
    
    public void setVtName(String vtName) {
        this.vtName = vtName;
    }




}


