package com.gwac.model;
// Generated 2014-8-30 13:00:35 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VariationType generated by hbm2java
 */
@Entity
@Table(name="variation_type"
    ,schema="public"
)
public class VariationType  implements java.io.Serializable {


     private long vtId;
     private String vtName;

    public VariationType() {
    }

	
    public VariationType(long vtId) {
        this.vtId = vtId;
    }
    public VariationType(long vtId, String vtName) {
       this.vtId = vtId;
       this.vtName = vtName;
    }
   
     @Id 

    
    @Column(name="vt_id", unique=true, nullable=false)
    public long getVtId() {
        return this.vtId;
    }
    
    public void setVtId(long vtId) {
        this.vtId = vtId;
    }

    
    @Column(name="vt_name")
    public String getVtName() {
        return this.vtName;
    }
    
    public void setVtName(String vtName) {
        this.vtName = vtName;
    }




}


