package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataProcessMachine generated by hbm2java
 */
@Entity
@Table(name = "camera", schema = "public"
)
public class Camera implements java.io.Serializable {

  private int cameraId;
  private String name;
  private Integer mountId;
  private Integer curProcessNumber;
  private Date monitorImageTime;
  private Date lastActiveTime;
  private Short curSkyId;
  private Integer firstRecordNumber;
  private Integer status;
  private String comment;
  private String cameraType;

  public Camera() {
  }

  public Camera(int cameraId) {
    this.cameraId = cameraId;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "camera_seq")
  @SequenceGenerator(name = "camera_seq", sequenceName = "camera_id_seq")
  @Column(name = "camera_id", unique = true, nullable = false)
  public int getCameraId() {
    return this.cameraId;
  }

  public void setCameraId(int cameraId) {
    this.cameraId = cameraId;
  }

  @Column(name = "name")
  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  @Column(name = "cur_process_number")
  public Integer getCurProcessNumber() {
    return this.curProcessNumber;
  }

  public void setCurProcessNumber(Integer curProcessNumber) {
    this.curProcessNumber = curProcessNumber;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "monitor_image_time", length = 29)
  public Date getMonitorImageTime() {
    return this.monitorImageTime;
  }

  public void setMonitorImageTime(Date monitorImageTime) {
    this.monitorImageTime = monitorImageTime;
  }

//  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "last_active_time", length = 29)
  public Date getLastActiveTime() {
    return this.lastActiveTime;
  }

  public void setLastActiveTime(Date lastActiveTime) {
    this.lastActiveTime = lastActiveTime;
  }

  @Column(name = "cur_sky_id")
  public Short getCurSkyId() {
    return this.curSkyId;
  }

  public void setCurSkyId(Short curSkyId) {
    this.curSkyId = curSkyId;
  }

  @Column(name = "first_record_number")
  public Integer getFirstRecordNumber() {
    return this.firstRecordNumber;
  }

  public void setFirstRecordNumber(Integer firstRecordNumber) {
    this.firstRecordNumber = firstRecordNumber;
  }

  /**
   * @return the mountId
   */
  @Column(name = "mount_id")
  public Integer getMountId() {
    return mountId;
  }

  /**
   * @param mountId the mountId to set
   */
  public void setMountId(Integer mountId) {
    this.mountId = mountId;
  }

  /**
   * @return the status
   */
  @Column(name = "status")
  public Integer getStatus() {
    return status;
  }

  /**
   * @param status the status to set
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

  /**
   * @return the comment
   */
  @Column(name = "comment")
  public String getComment() {
    return comment;
  }

  /**
   * @param comment the comment to set
   */
  public void setComment(String comment) {
    this.comment = comment;
  }

  /**
   * @return the cameraType
   */
  @Column(name = "camera_type")
  public String getCameraType() {
    return cameraType;
  }

  /**
   * @param cameraType the cameraType to set
   */
  public void setCameraType(String cameraType) {
    this.cameraType = cameraType;
  }

}
