package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * OtLevel2 generated by hbm2java
 */
@Entity
@Table(name = "cross_object",
	 schema = "public"
)
public class CrossObject implements java.io.Serializable {

  private long coId;
  private Long ctId;
  private Date foundTimeUtc;
  private Integer camId;
  private Integer skyId;
  private Float x;
  private Float y;
  private Float xtemp;
  private Float ytemp;
  private Float ra;
  private Float dec;
  private Float mag;
  private Integer firstFfNumber;
  private Integer lastFfNumber;
  private Integer total;
  private String dateStr;
  private Short otType;
  private Short isMatch;
  private Boolean cvsMatch;
  private Boolean rc3Match;
  private Boolean minorPlanetMatch;
  private Boolean hisMatch;
  private Boolean otherMatch;
  private Boolean usnoMatch;
  private Boolean badMatch;
  private Short lookBackResult;
  private Short followUpResult;
  private Short foCount;
  private Float lookBackCnn;
  private Float probability;

  public CrossObject() {
  }

  public CrossObject(long coId) {
    this.coId = coId;
  }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49")
    ,
    @Parameter(name = "sequence", value = "cross_o_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")

  @Column(name = "co_id", unique = true, nullable = false)
  public long getCoId() {
    return this.coId;
  }

  public void setCoId(long coId) {
    this.coId = coId;
  }

  @Column(name = "ct_id")
  public Long getCtId() {
    return this.ctId;
  }

  public void setCtId(Long ctId) {
    this.ctId = ctId;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "found_time_utc", length = 29)
  public Date getFoundTimeUtc() {
    return this.foundTimeUtc;
  }

  public void setFoundTimeUtc(Date foundTimeUtc) {
    this.foundTimeUtc = foundTimeUtc;
  }

  @Column(name = "cam_id")
  public Integer getCamId() {
    return this.camId;
  }

  public void setCamId(Integer camId) {
    this.camId = camId;
  }

  @Column(name = "sky_id")
  public Integer getSkyId() {
    return this.skyId;
  }

  public void setSkyId(Integer skyId) {
    this.skyId = skyId;
  }

  @Column(name = "x", precision = 8, scale = 8)
  public Float getX() {
    return this.x;
  }

  public void setX(Float x) {
    this.x = x;
  }

  @Column(name = "y", precision = 8, scale = 8)
  public Float getY() {
    return this.y;
  }

  public void setY(Float y) {
    this.y = y;
  }

  @Column(name = "x_temp", precision = 8, scale = 8)
  public Float getXtemp() {
    return this.xtemp;
  }

  public void setXtemp(Float xtemp) {
    this.xtemp = xtemp;
  }

  @Column(name = "y_temp", precision = 8, scale = 8)
  public Float getYtemp() {
    return this.ytemp;
  }

  public void setYtemp(Float ytemp) {
    this.ytemp = ytemp;
  }

  @Column(name = "ra", precision = 8, scale = 8)
  public Float getRa() {
    return this.ra;
  }

  public void setRa(Float ra) {
    this.ra = ra;
  }

  @Column(name = "dec", precision = 8, scale = 8)
  public Float getDec() {
    return this.dec;
  }

  public void setDec(Float dec) {
    this.dec = dec;
  }

  @Column(name = "mag", precision = 8, scale = 8)
  public Float getMag() {
    return this.mag;
  }

  public void setMag(Float mag) {
    this.mag = mag;
  }

  @Column(name = "first_ff_number")
  public Integer getFirstFfNumber() {
    return this.firstFfNumber;
  }

  public void setFirstFfNumber(Integer firstFfNumber) {
    this.firstFfNumber = firstFfNumber;
  }

  @Column(name = "last_ff_number")
  public Integer getLastFfNumber() {
    return this.lastFfNumber;
  }

  public void setLastFfNumber(Integer lastFfNumber) {
    this.lastFfNumber = lastFfNumber;
  }

  @Column(name = "total")
  public Integer getTotal() {
    return this.total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  @Column(name = "date_str", length = 6)
  public String getDateStr() {
    return this.dateStr;
  }

  public void setDateStr(String dateStr) {
    this.dateStr = dateStr;
  }

  @Column(name = "ot_type")
  public Short getOtType() {
    return this.otType;
  }

  public void setOtType(Short otType) {
    this.otType = otType;
  }

  @Column(name = "is_match")
  public Short getIsMatch() {
    return this.isMatch;
  }

  public void setIsMatch(Short isMatch) {
    this.isMatch = isMatch;
  }

  /**
   * @return the cvsMatch
   */
  @Column(name = "cvs_match")
  public Boolean getCvsMatch() {
    return cvsMatch;
  }

  /**
   * @param cvsMatch the cvsMatch to set
   */
  public void setCvsMatch(Boolean cvsMatch) {
    this.cvsMatch = cvsMatch;
  }

  /**
   * @return the rc3Match
   */
  @Column(name = "rc3_match")
  public Boolean getRc3Match() {
    return rc3Match;
  }

  /**
   * @param rc3Match the rc3Match to set
   */
  public void setRc3Match(Boolean rc3Match) {
    this.rc3Match = rc3Match;
  }

  /**
   * @return the minorPlanetMatch
   */
  @Column(name = "minor_planet_match")
  public Boolean getMinorPlanetMatch() {
    return minorPlanetMatch;
  }

  /**
   * @param minorPlanetMatch the minorPlanetMatch to set
   */
  public void setMinorPlanetMatch(Boolean minorPlanetMatch) {
    this.minorPlanetMatch = minorPlanetMatch;
  }

  /**
   * @return the ot2HisMatch
   */
  @Column(name = "his_match")
  public Boolean getHisMatch() {
    return hisMatch;
  }

  /**
   * @param hisMatch the hisMatch to set
   */
  public void setHisMatch(Boolean hisMatch) {
    this.hisMatch = hisMatch;
  }

  /**
   * @return the otherMatch
   */
  @Column(name = "other_match")
  public Boolean getOtherMatch() {
    return otherMatch;
  }

  /**
   * @param otherMatch the otherMatch to set
   */
  public void setOtherMatch(Boolean otherMatch) {
    this.otherMatch = otherMatch;
  }

  /**
   * @return the usnoMatch
   */
  @Column(name = "usno_match")
  public Boolean getUsnoMatch() {
    return usnoMatch;
  }

  /**
   * @param usnoMatch the usnoMatch to set
   */
  public void setUsnoMatch(Boolean usnoMatch) {
    this.usnoMatch = usnoMatch;
  }

  /**
   * @return the usnoMatch
   */
  @Column(name = "bad_match")
  public Boolean getBadMatch() {
    return badMatch;
  }

  public void setBadMatch(Boolean badMatch) {
    this.badMatch = badMatch;
  }

  /**
   * @return the lookBackResult
   */
  @Column(name = "look_back_result")
  public Short getLookBackResult() {
    return lookBackResult;
  }

  /**
   * @param lookBackResult the lookBackResult to set
   */
  public void setLookBackResult(Short lookBackResult) {
    this.lookBackResult = lookBackResult;
  }

  /**
   * @return the followUpResult follow_up_result
   */
  @Column(name = "follow_up_result")
  public Short getFollowUpResult() {
    return followUpResult;
  }

  /**
   * @param followUpResult the followUpResult to set
   */
  public void setFollowUpResult(Short followUpResult) {
    this.followUpResult = followUpResult;
  }

  @Column(name = "fo_count")
  public Short getFoCount() {
    return this.foCount;
  }

  public void setFoCount(Short foCount) {
    this.foCount = foCount;
  }

  /**
   * @return the lookBackCnn
   */
  @Column(name = "look_back_cnn")
  public Float getLookBackCnn() {
    return lookBackCnn;
  }

  /**
   * @param lookBackCnn the lookBackCnn to set
   */
  public void setLookBackCnn(Float lookBackCnn) {
    this.lookBackCnn = lookBackCnn;
  }

  /**
   * @return the probability
   */
  @Column(name = "probability")
  public Float getProbability() {
    return probability;
  }

  /**
   * @param probability the probability to set
   */
  public void setProbability(Float probability) {
    this.probability = probability;
  }
}
