package com.gwac.model;
// Generated 2017-1-10 20:46:20 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FileNumber generated by hbm2java
 */
@Entity
@Table(name = "file_number", schema = "public"
)
public class FileNumber implements java.io.Serializable {

  private long fnId;
  private Integer skyId;
  private Integer camId;
  private String dateStr;
  private Integer ffNumber;

  public FileNumber() {
  }

  public FileNumber(long fnId) {
    this.fnId = fnId;
  }

  public FileNumber(long fnId, Integer skyId, Integer camId, String dateStr, Integer ffNumber) {
    this.fnId = fnId;
    this.skyId = skyId;
    this.camId = camId;
    this.dateStr = dateStr;
    this.ffNumber = ffNumber;
  }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "fn_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "fn_id", unique = true, nullable = false)
  public long getFnId() {
    return this.fnId;
  }

  public void setFnId(long fnId) {
    this.fnId = fnId;
  }

  @Column(name = "sky_id")
  public Integer getSkyId() {
    return this.skyId;
  }

  public void setSkyId(Integer skyId) {
    this.skyId = skyId;
  }

  @Column(name = "cam_id")
  public Integer getCamId() {
    return this.camId;
  }

  public void setCamId(Integer camId) {
    this.camId = camId;
  }

  @Column(name = "date_Str")
  public String getDateStr() {
    return this.dateStr;
  }

  public void setDateStr(String dateStr) {
    this.dateStr = dateStr;
  }

  @Column(name = "ff_number")
  public Integer getFfNumber() {
    return this.ffNumber;
  }

  public void setFfNumber(Integer ffNumber) {
    this.ffNumber = ffNumber;
  }

}
