package com.gwac.model;
// Generated 2017-1-10 20:46:20 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FitsFile2 generated by hbm2java
 */
@Entity
@Table(name = "fits_file2", schema = "public"
)
public class FitsFile2 implements java.io.Serializable {

  private long ffId;
  private Integer ffNumber;
  private Integer mountId;
  private Integer camId;
  private Integer skyId;
  private String imgName;
  private String imgPath;
  private Date genTime;
  private Integer timeSubSecond;

  public FitsFile2() {
  }

  public FitsFile2(long ffId) {
    this.ffId = ffId;
  }

  public FitsFile2(long ffId, Integer ffNumber, Integer mountId, Integer camId, Integer skyId, String imgName, String imgPath, Date genTime) {
    this.ffId = ffId;
    this.ffNumber = ffNumber;
    this.mountId = mountId;
    this.camId = camId;
    this.skyId = skyId;
    this.imgName = imgName;
    this.imgPath = imgPath;
    this.genTime = genTime;
  }

  @Id
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "ff_id_seq2")})
  @GeneratedValue(generator = "generator")
  @Column(name = "ff_id", unique = true, nullable = false)
  public long getFfId() {
    return this.ffId;
  }

  public void setFfId(long ffId) {
    this.ffId = ffId;
  }

  @Column(name = "ff_number")
  public Integer getFfNumber() {
    return this.ffNumber;
  }

  public void setFfNumber(Integer ffNumber) {
    this.ffNumber = ffNumber;
  }

  @Column(name = "mount_id")
  public Integer getMountId() {
    return this.mountId;
  }

  public void setMountId(Integer mountId) {
    this.mountId = mountId;
  }

  @Column(name = "cam_id")
  public Integer getCamId() {
    return this.camId;
  }

  public void setCamId(Integer camId) {
    this.camId = camId;
  }

  @Column(name = "sky_id")
  public Integer getSkyId() {
    return this.skyId;
  }

  public void setSkyId(Integer skyId) {
    this.skyId = skyId;
  }

  @Column(name = "img_name")
  public String getImgName() {
    return this.imgName;
  }

  public void setImgName(String imgName) {
    this.imgName = imgName;
  }

  @Column(name = "img_path")
  public String getImgPath() {
    return this.imgPath;
  }

  public void setImgPath(String imgPath) {
    this.imgPath = imgPath;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "gen_time", length = 29)
  public Date getGenTime() {
    return this.genTime;
  }

  public void setGenTime(Date genTime) {
    this.genTime = genTime;
  }

  /**
   * @return the timeSubSecond
   */
  @Column(name = "time_sub_second")
  public Integer getTimeSubSecond() {
    return timeSubSecond;
  }

  /**
   * @param timeSubSecond the timeSubSecond to set
   */
  public void setTimeSubSecond(Integer timeSubSecond) {
    this.timeSubSecond = timeSubSecond;
  }

}
