package com.gwac.model;
// Generated 2017-1-10 20:46:20 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FitsFile2 generated by hbm2java
 */
@Entity
@Table(name = "fits_file2", schema = "public"
)
public class FitsFile2Show implements java.io.Serializable {

  private long ffId;
  private Integer ffNumber;
  private Integer mountId;
  private Integer camId;
  private Integer skyId;
  private String imgName;
  private String imgPath;
  private Date genTime;
  private String groupName;
  private String unitName;
  private String camName;
  private String gridName;
  private String fieldName;

  public FitsFile2Show() {
  }

  public FitsFile2Show(long ffId) {
    this.ffId = ffId;
  }

  @Id
  @Column(name = "ff_id", unique = true, nullable = false)
  public long getFfId() {
    return this.ffId;
  }

  public void setFfId(long ffId) {
    this.ffId = ffId;
  }

  @Column(name = "ff_number")
  public Integer getFfNumber() {
    return this.ffNumber;
  }

  public void setFfNumber(Integer ffNumber) {
    this.ffNumber = ffNumber;
  }

  @Column(name = "mount_id")
  public Integer getMountId() {
    return this.mountId;
  }

  public void setMountId(Integer mountId) {
    this.mountId = mountId;
  }

  @Column(name = "cam_id")
  public Integer getCamId() {
    return this.camId;
  }

  public void setCamId(Integer camId) {
    this.camId = camId;
  }

  @Column(name = "sky_id")
  public Integer getSkyId() {
    return this.skyId;
  }

  public void setSkyId(Integer skyId) {
    this.skyId = skyId;
  }

  @Column(name = "img_name")
  public String getImgName() {
    return this.imgName;
  }

  public void setImgName(String imgName) {
    this.imgName = imgName;
  }

  @Column(name = "img_path")
  public String getImgPath() {
    return this.imgPath;
  }

  public void setImgPath(String imgPath) {
    this.imgPath = imgPath;
  }

  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "gen_time", length = 29)
  public Date getGenTime() {
    return this.genTime;
  }

  public void setGenTime(Date genTime) {
    this.genTime = genTime;
  }

  /**
   * @return the groupName
   */
  @Column(name = "group_name")
  public String getGroupName() {
    return groupName;
  }

  /**
   * @param groupName the groupName to set
   */
  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  /**
   * @return the unitName
   */
  @Column(name = "unit_name")
  public String getUnitName() {
    return unitName;
  }

  /**
   * @param unitName the unitName to set
   */
  public void setUnitName(String unitName) {
    this.unitName = unitName;
  }

  /**
   * @return the camName
   */
  @Column(name = "cam_name")
  public String getCamName() {
    return camName;
  }

  /**
   * @param camName the camName to set
   */
  public void setCamName(String camName) {
    this.camName = camName;
  }

  /**
   * @return the gridName
   */
  @Column(name = "grid_name")
  public String getGridName() {
    return gridName;
  }

  /**
   * @param gridName the gridName to set
   */
  public void setGridName(String gridName) {
    this.gridName = gridName;
  }

  /**
   * @return the fieldName
   */
  @Column(name = "field_name")
  public String getFieldName() {
    return fieldName;
  }

  /**
   * @param fieldName the fieldName to set
   */
  public void setFieldName(String fieldName) {
    this.fieldName = fieldName;
  }

}
