package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * MatchTable generated by hbm2java
 */
@Entity
@Table(name="match_table"
    ,schema="public"
)
public class MatchTable  implements java.io.Serializable {


     private short mtId;
     private String matchTypeName;
     private String matchTableName;
     private String comments;

    public MatchTable() {
    }

	
    public MatchTable(short mtId) {
        this.mtId = mtId;
    }
    public MatchTable(short mtId, String matchTypeName, String matchTableName, String comments) {
       this.mtId = mtId;
       this.matchTypeName = matchTypeName;
       this.matchTableName = matchTableName;
       this.comments = comments;
    }
   
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "mt_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "mt_id", unique = true, nullable = false)
    public short getMtId() {
        return this.mtId;
    }
    
    public void setMtId(short mtId) {
        this.mtId = mtId;
    }

    
    @Column(name="match_type_name")
    public String getMatchTypeName() {
        return this.matchTypeName;
    }
    
    public void setMatchTypeName(String matchTypeName) {
        this.matchTypeName = matchTypeName;
    }

    
    @Column(name="match_table_name", length=64)
    public String getMatchTableName() {
        return this.matchTableName;
    }
    
    public void setMatchTableName(String matchTableName) {
        this.matchTableName = matchTableName;
    }

    
    @Column(name="comments", length=1024)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }




}


