package com.gwac.model;
// Generated 2016-12-4 18:51:52 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MoveObjectRecord generated by hbm2java
 */
@Entity
@Table(name="move_object_record"
    ,schema="public"
)
public class MoveObjectRecord  implements java.io.Serializable {


     private long oorId;
     private Float speedRa;
     private Float speedDec;
     private Float speedGreatCircle;
     private Long movId;

    public MoveObjectRecord() {
    }

	
    public MoveObjectRecord(long oorId) {
        this.oorId = oorId;
    }
    public MoveObjectRecord(long oorId, Float speedRa, Float speedDec, Float speedGreatCircle, Long movId) {
       this.oorId = oorId;
       this.speedRa = speedRa;
       this.speedDec = speedDec;
       this.speedGreatCircle = speedGreatCircle;
       this.movId = movId;
    }
   
     @Id 

    
    @Column(name="oor_id", unique=true, nullable=false)
    public long getOorId() {
        return this.oorId;
    }
    
    public void setOorId(long oorId) {
        this.oorId = oorId;
    }

    
    @Column(name="speed_ra", precision=8, scale=8)
    public Float getSpeedRa() {
        return this.speedRa;
    }
    
    public void setSpeedRa(Float speedRa) {
        this.speedRa = speedRa;
    }

    
    @Column(name="speed_dec", precision=8, scale=8)
    public Float getSpeedDec() {
        return this.speedDec;
    }
    
    public void setSpeedDec(Float speedDec) {
        this.speedDec = speedDec;
    }

    
    @Column(name="speed_great_circle", precision=8, scale=8)
    public Float getSpeedGreatCircle() {
        return this.speedGreatCircle;
    }
    
    public void setSpeedGreatCircle(Float speedGreatCircle) {
        this.speedGreatCircle = speedGreatCircle;
    }

    
    @Column(name="mov_id")
    public Long getMovId() {
        return this.movId;
    }
    
    public void setMovId(Long movId) {
        this.movId = movId;
    }




}


