package com.gwac.model;
// Generated 2017-1-10 20:46:20 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObjectRelationId generated by hbm2java
 */
@Embeddable
public class ObjectRelationId  implements java.io.Serializable {


     private Integer parentObjId;
     private Integer childObjId;

    public ObjectRelationId() {
    }

    public ObjectRelationId(Integer parentObjId, Integer childObjId) {
       this.parentObjId = parentObjId;
       this.childObjId = childObjId;
    }
   


    @Column(name="parent_obj_id")
    public Integer getParentObjId() {
        return this.parentObjId;
    }
    
    public void setParentObjId(Integer parentObjId) {
        this.parentObjId = parentObjId;
    }


    @Column(name="child_obj_id")
    public Integer getChildObjId() {
        return this.childObjId;
    }
    
    public void setChildObjId(Integer childObjId) {
        this.childObjId = childObjId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ObjectRelationId) ) return false;
		 ObjectRelationId castOther = ( ObjectRelationId ) other; 
         
		 return ( (this.getParentObjId()==castOther.getParentObjId()) || ( this.getParentObjId()!=null && castOther.getParentObjId()!=null && this.getParentObjId().equals(castOther.getParentObjId()) ) )
 && ( (this.getChildObjId()==castOther.getChildObjId()) || ( this.getChildObjId()!=null && castOther.getChildObjId()!=null && this.getChildObjId().equals(castOther.getChildObjId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getParentObjId() == null ? 0 : this.getParentObjId().hashCode() );
         result = 37 * result + ( getChildObjId() == null ? 0 : this.getChildObjId().hashCode() );
         return result;
   }   


}


