package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataProcessMachine generated by hbm2java
 */
@Entity
@Table(name = "camera", schema = "public"
)
public class Ot2StreamNodeTime implements java.io.Serializable {

  private long otId;
  private Long oorId1;
  private Long oorId2;
  private Date ot2GenTime;
  private Date lookbackTime;
  private Date lookupTime;
  private Date lookupResultTime;

  public Ot2StreamNodeTime() {
  }

  public Ot2StreamNodeTime(int otId) {
    this.otId = otId;
  }

  @Id
  @Column(name = "ot_id", unique = true, nullable = false)
  public long getOtId() {
    return otId;
  }

  /**
   * @param otId the otId to set
   */
  public void setOtId(long otId) {
    this.otId = otId;
  }

  /**
   * @return the oorId1
   */
  @Column(name = "oor_id1")
  public Long getOorId1() {
    return oorId1;
  }

  /**
   * @param oorId1 the oorId1 to set
   */
  public void setOorId1(Long oorId1) {
    this.oorId1 = oorId1;
  }

  /**
   * @return the oorId2
   */
  @Column(name = "oor_id2")
  public Long getOorId2() {
    return oorId2;
  }

  /**
   * @param oorId2 the oorId2 to set
   */
  public void setOorId2(Long oorId2) {
    this.oorId2 = oorId2;
  }

  /**
   * @return the ot2GenTime
   */
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "ot2_gen_time", length = 29)
  public Date getOt2GenTime() {
    return ot2GenTime;
  }

  /**
   * @param ot2GenTime the ot2GenTime to set
   */
  public void setOt2GenTime(Date ot2GenTime) {
    this.ot2GenTime = ot2GenTime;
  }

  /**
   * @return the lookbackTime
   */
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "lookback_time", length = 29)
  public Date getLookbackTime() {
    return lookbackTime;
  }

  /**
   * @param lookbackTime the lookbackTime to set
   */
  public void setLookbackTime(Date lookbackTime) {
    this.lookbackTime = lookbackTime;
  }

  /**
   * @return the lookupTime
   */
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "lookup_time", length = 29)
  public Date getLookupTime() {
    return lookupTime;
  }

  /**
   * @param lookupTime the lookupTime to set
   */
  public void setLookupTime(Date lookupTime) {
    this.lookupTime = lookupTime;
  }

  /**
   * @return the lookupResultTime
   */
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "lookup_result_time", length = 29)
  public Date getLookupResultTime() {
    return lookupResultTime;
  }

  /**
   * @param lookupResultTime the lookupResultTime to set
   */
  public void setLookupResultTime(Date lookupResultTime) {
    this.lookupResultTime = lookupResultTime;
  }

}
