package com.gwac.model;
// Generated 2015-11-5 20:06:22 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * OtComment generated by hbm2java
 */
@Entity
@Table(name="ot_comment"
    ,schema="public"
)
public class OtComment  implements java.io.Serializable {


     private long ocId;
     private Long otId;
     private Integer uiId;
     private String comments;
     private Long parentId;
     private Date genTime;
     private Integer agreeNumber;
     private Integer disagreeNumber;

    public OtComment() {
    }

	
    public OtComment(long ocId) {
        this.ocId = ocId;
    }
    public OtComment(long ocId, Long otId, Integer uiId, String comments, Long parentId, Date genTime, Integer agreeNumber, Integer disagreeNumber) {
       this.ocId = ocId;
       this.otId = otId;
       this.uiId = uiId;
       this.comments = comments;
       this.parentId = parentId;
       this.genTime = genTime;
       this.agreeNumber = agreeNumber;
       this.disagreeNumber = disagreeNumber;
    }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "co_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
    @Column(name="oc_id", unique=true, nullable=false)
    public long getOcId() {
        return this.ocId;
    }
    
    public void setOcId(long ocId) {
        this.ocId = ocId;
    }

    
    @Column(name="ot_id")
    public Long getOtId() {
        return this.otId;
    }
    
    public void setOtId(Long otId) {
        this.otId = otId;
    }

    
    @Column(name="ui_id")
    public Integer getUiId() {
        return this.uiId;
    }
    
    public void setUiId(Integer uiId) {
        this.uiId = uiId;
    }

    
    @Column(name="comments", length=1024)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="parent_id")
    public Long getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="gen_time", length=29)
    public Date getGenTime() {
        return this.genTime;
    }
    
    public void setGenTime(Date genTime) {
        this.genTime = genTime;
    }

    
    @Column(name="agree_number")
    public Integer getAgreeNumber() {
        return this.agreeNumber;
    }
    
    public void setAgreeNumber(Integer agreeNumber) {
        this.agreeNumber = agreeNumber;
    }

    
    @Column(name="disagree_number")
    public Integer getDisagreeNumber() {
        return this.disagreeNumber;
    }
    
    public void setDisagreeNumber(Integer disagreeNumber) {
        this.disagreeNumber = disagreeNumber;
    }




}


