package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * OtLevel2 generated by hbm2java
 */
@Entity
@Table(name="ot_level2"
    ,schema="public"
)
public class OtLevel2  implements java.io.Serializable {


     private long otId;
     private String name;
     private Float ra;
     private Float dec;
     private Date foundTimeUtc;
     private String identify;
     private Float xtemp;
     private Float ytemp;
     private Integer lastFfNumber;
     private Integer total;
     private Boolean isRecognize;
     private Short otType;
     private String comments;
     private Integer dpmId;
     private String dateStr;
     private Boolean allFileCutted;
     private Integer firstFfNumber;
     private Integer cuttedFfNumber;
     private Short isMatch;
     private Boolean firstNMark;
     private Short skyId;
     private Character dataProduceMethod;
     private Short foCount;
     private Float mag;
     private Short cvsMatch;
     private Short rc3Match;
     private Short minorPlanetMatch;
     private Short ot2HisMatch;
     private Short otherMatch;
     private Short usnoMatch;
     private Short lookBackResult;
     private Short followUpResult;
     private Float lookBackCnn;
     private Float probability;

    public OtLevel2() {
    }

	
    public OtLevel2(long otId) {
        this.otId = otId;
    }
   
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "ot_leve2_seq")})
     @Id 
  @GeneratedValue(generator = "generator")

  @Column(name = "ot_id", unique = true, nullable = false)
    public long getOtId() {
        return this.otId;
    }
    
    public void setOtId(long otId) {
        this.otId = otId;
    }

    
    @Column(name="name", length=13)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="ra", precision=8, scale=8)
    public Float getRa() {
        return this.ra;
    }
    
    public void setRa(Float ra) {
        this.ra = ra;
    }

    
    @Column(name="dec", precision=8, scale=8)
    public Float getDec() {
        return this.dec;
    }
    
    public void setDec(Float dec) {
        this.dec = dec;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="found_time_utc", length=29)
    public Date getFoundTimeUtc() {
        return this.foundTimeUtc;
    }
    
    public void setFoundTimeUtc(Date foundTimeUtc) {
        this.foundTimeUtc = foundTimeUtc;
    }

    
    @Column(name="identify", length=21)
    public String getIdentify() {
        return this.identify;
    }
    
    public void setIdentify(String identify) {
        this.identify = identify;
    }

    
    @Column(name="xtemp", precision=8, scale=8)
    public Float getXtemp() {
        return this.xtemp;
    }
    
    public void setXtemp(Float xtemp) {
        this.xtemp = xtemp;
    }

    
    @Column(name="ytemp", precision=8, scale=8)
    public Float getYtemp() {
        return this.ytemp;
    }
    
    public void setYtemp(Float ytemp) {
        this.ytemp = ytemp;
    }

    
    @Column(name="last_ff_number")
    public Integer getLastFfNumber() {
        return this.lastFfNumber;
    }
    
    public void setLastFfNumber(Integer lastFfNumber) {
        this.lastFfNumber = lastFfNumber;
    }

    
    @Column(name="total")
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }

    
    @Column(name="is_recognize")
    public Boolean getIsRecognize() {
        return this.isRecognize;
    }
    
    public void setIsRecognize(Boolean isRecognize) {
        this.isRecognize = isRecognize;
    }

    
    @Column(name="ot_type")
    public Short getOtType() {
        return this.otType;
    }
    
    public void setOtType(Short otType) {
        this.otType = otType;
    }

    
    @Column(name="comments", length=1024)
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

    
    @Column(name="dpm_id")
    public Integer getDpmId() {
        return this.dpmId;
    }
    
    public void setDpmId(Integer dpmId) {
        this.dpmId = dpmId;
    }

    
    @Column(name="date_str", length=6)
    public String getDateStr() {
        return this.dateStr;
    }
    
    public void setDateStr(String dateStr) {
        this.dateStr = dateStr;
    }

    
    @Column(name="all_file_cutted")
    public Boolean getAllFileCutted() {
        return this.allFileCutted;
    }
    
    public void setAllFileCutted(Boolean allFileCutted) {
        this.allFileCutted = allFileCutted;
    }

    
    @Column(name="first_ff_number")
    public Integer getFirstFfNumber() {
        return this.firstFfNumber;
    }
    
    public void setFirstFfNumber(Integer firstFfNumber) {
        this.firstFfNumber = firstFfNumber;
    }

    
    @Column(name="cutted_ff_number")
    public Integer getCuttedFfNumber() {
        return this.cuttedFfNumber;
    }
    
    public void setCuttedFfNumber(Integer cuttedFfNumber) {
        this.cuttedFfNumber = cuttedFfNumber;
    }

    
    @Column(name="is_match")
    public Short getIsMatch() {
        return this.isMatch;
    }
    
    public void setIsMatch(Short isMatch) {
        this.isMatch = isMatch;
    }

    
    @Column(name="first_n_mark")
    public Boolean getFirstNMark() {
        return this.firstNMark;
    }
    
    public void setFirstNMark(Boolean firstNMark) {
        this.firstNMark = firstNMark;
    }

    
    @Column(name="sky_id")
    public Short getSkyId() {
        return this.skyId;
    }
    
    public void setSkyId(Short skyId) {
        this.skyId = skyId;
    }

    
    @Column(name="data_produce_method", length=1)
    public Character getDataProduceMethod() {
        return this.dataProduceMethod;
    }
    
    public void setDataProduceMethod(Character dataProduceMethod) {
        this.dataProduceMethod = dataProduceMethod;
    }

  /**
   * @return the foCount
   */
    @Column(name="fo_count")
  public Short getFoCount() {
    return foCount;
  }

  /**
   * @param foCount the foCount to set
   */
  public void setFoCount(Short foCount) {
    this.foCount = foCount;
  }

  /**
   * @return the mag
   */
    @Column(name="mag")
  public Float getMag() {
    return mag;
  }

  /**
   * @param mag the mag to set
   */
  public void setMag(Float mag) {
    this.mag = mag;
  }

  /**
   * @return the cvsMatch
   */
    @Column(name="cvs_match")
  public Short getCvsMatch() {
    return cvsMatch;
  }

  /**
   * @param cvsMatch the cvsMatch to set
   */
  public void setCvsMatch(Short cvsMatch) {
    this.cvsMatch = cvsMatch;
  }

  /**
   * @return the rc3Match
   */
    @Column(name="rc3_match")
  public Short getRc3Match() {
    return rc3Match;
  }

  /**
   * @param rc3Match the rc3Match to set
   */
  public void setRc3Match(Short rc3Match) {
    this.rc3Match = rc3Match;
  }

  /**
   * @return the minorPlanetMatch
   */
    @Column(name="minor_planet_match")
  public Short getMinorPlanetMatch() {
    return minorPlanetMatch;
  }

  /**
   * @param minorPlanetMatch the minorPlanetMatch to set
   */
  public void setMinorPlanetMatch(Short minorPlanetMatch) {
    this.minorPlanetMatch = minorPlanetMatch;
  }

  /**
   * @return the ot2HisMatch
   */
    @Column(name="ot2_his_match")
  public Short getOt2HisMatch() {
    return ot2HisMatch;
  }

  /**
   * @param ot2HisMatch the ot2HisMatch to set
   */
  public void setOt2HisMatch(Short ot2HisMatch) {
    this.ot2HisMatch = ot2HisMatch;
  }

  /**
   * @return the otherMatch
   */
    @Column(name="other_match")
  public Short getOtherMatch() {
    return otherMatch;
  }

  /**
   * @param otherMatch the otherMatch to set 
   */
  public void setOtherMatch(Short otherMatch) {
    this.otherMatch = otherMatch;
  }

  /**
   * @return the usnoMatch
   */
    @Column(name="usno_match")
  public Short getUsnoMatch() {
    return usnoMatch;
  }

  /**
   * @param usnoMatch the usnoMatch to set
   */
  public void setUsnoMatch(Short usnoMatch) {
    this.usnoMatch = usnoMatch;
  }

  /**
   * @return the lookBackResult 
   */
    @Column(name="look_back_result")
  public Short getLookBackResult() {
    return lookBackResult;
  }

  /**
   * @param lookBackResult the lookBackResult to set
   */
  public void setLookBackResult(Short lookBackResult) {
    this.lookBackResult = lookBackResult;
  }

  /**
   * @return the followUpResult follow_up_result
   */
    @Column(name="follow_up_result")
  public Short getFollowUpResult() {
    return followUpResult;
  }

  /**
   * @param followUpResult the followUpResult to set
   */
  public void setFollowUpResult(Short followUpResult) {
    this.followUpResult = followUpResult;
  }

  /**
   * @return the lookBackCnn
   */
  @Column(name="look_back_cnn")
  public Float getLookBackCnn() {
    return lookBackCnn;
  }

  /**
   * @param lookBackCnn the lookBackCnn to set
   */
  public void setLookBackCnn(Float lookBackCnn) {
    this.lookBackCnn = lookBackCnn;
  }

  /**
   * @return the probability
   */
  @Column(name="probability")
  public Float getProbability() {
    return probability;
  }

  /**
   * @param probability the probability to set
   */
  public void setProbability(Float probability) {
    this.probability = probability;
  }
}


