package com.gwac.model;
// Generated May 5, 2014 8:56:32 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OtObserveRecordShow generated by hbm2java
 */
@Entity
@Table(name = "ot_observe_record", schema = "public"
)
public class OtObserveRecordMovObj implements java.io.Serializable {

  private long oorId;
  private Long otId;
  private Long ffId;
  private String ffName;
  private Float raD;
  private Float decD;
  private Float x;
  private Float y;
  private Float XTemp;
  private Float YTemp;
  private Date dateUt;
  private Float flux;
  private Float magAper;
  private Float magerrAper;
  private Float ellipticity;
  private Float classStar;
  private Boolean otFlag;
  private Integer ffNumber;
  private Integer dpmId;
  private String dateStr;
  private Short skyId;
  private Float distance;
  private Float deltamag;
  private Character dataProduceMethod;
  private Integer timeSubSecond;

  public OtObserveRecordMovObj() {
  }


  @Id
  @Column(name = "oor_id")
  public long getOorId() {
    return this.oorId;
  }

  public void setOorId(long oorId) {
    this.oorId = oorId;
  }

  @Column(name = "ot_id")
  public Long getOtId() {
    return this.otId;
  }

  public void setOtId(Long otId) {
    this.otId = otId;
  }

  @Column(name = "ff_id")
  public Long getFfId() {
    return this.ffId;
  }

  public void setFfId(Long ffId) {
    this.ffId = ffId;
  }

  @Column(name = "ra_d")
  public Float getRaD() {
    return this.raD;
  }

  public void setRaD(Float raD) {
    this.raD = raD;
  }

  @Column(name = "dec_d")
  public Float getDecD() {
    return this.decD;
  }

  public void setDecD(Float decD) {
    this.decD = decD;
  }

  @Column(name = "x")
  public Float getX() {
    return this.x;
  }

  public void setX(Float x) {
    this.x = x;
  }

  @Column(name = "y")
  public Float getY() {
    return this.y;
  }

  public void setY(Float y) {
    this.y = y;
  }

  @Column(name = "x_temp")
  public Float getXTemp() {
    return this.XTemp;
  }

  public void setXTemp(Float XTemp) {
    this.XTemp = XTemp;
  }

  @Column(name = "y_temp")
  public Float getYTemp() {
    return this.YTemp;
  }

  public void setYTemp(Float YTemp) {
    this.YTemp = YTemp;
  }

  @Column(name = "date_ut")
  public Date getDateUt() {
    return this.dateUt;
  }

  public void setDateUt(Date dateUt) {
    this.dateUt = dateUt;
  }

  @Column(name = "flux")
  public Float getFlux() {
    return this.flux;
  }

  public void setFlux(Float flux) {
    this.flux = flux;
  }

  @Column(name = "mag_aper")
  public Float getMagAper() {
    return this.magAper;
  }

  public void setMagAper(Float magAper) {
    this.magAper = magAper;
  }

  @Column(name = "magerr_aper")
  public Float getMagerrAper() {
    return this.magerrAper;
  }

  public void setMagerrAper(Float magerrAper) {
    this.magerrAper = magerrAper;
  }

  @Column(name = "ellipticity")
  public Float getEllipticity() {
    return this.ellipticity;
  }

  public void setEllipticity(Float ellipticity) {
    this.ellipticity = ellipticity;
  }

  @Column(name = "class_star")
  public Float getClassStar() {
    return this.classStar;
  }

  public void setClassStar(Float classStar) {
    this.classStar = classStar;
  }

  @Column(name = "ot_flag")
  public Boolean getOtFlag() {
    return this.otFlag;
  }

  public void setOtFlag(Boolean otFlag) {
    this.otFlag = otFlag;
  }

  /**
   * @return the ffName
   */
  @Column(name = "ff_name")
  public String getFfName() {
    return ffName;
  }

  /**
   * @param ffName the ffName to set
   */
  public void setFfName(String ffName) {
    this.ffName = ffName;
  }

  @Column(name = "ff_number")
  public Integer getFfNumber() {
    return this.ffNumber;
  }

  public void setFfNumber(Integer ffNumber) {
    this.ffNumber = ffNumber;
  }

  @Column(name = "dpm_id")
  public Integer getDpmId() {
    return this.dpmId;
  }

  public void setDpmId(Integer dpmId) {
    this.dpmId = dpmId;
  }

  @Column(name = "date_str", length = 6)
  public String getDateStr() {
    return this.dateStr;
  }

  public void setDateStr(String dateStr) {
    this.dateStr = dateStr;
  }

  @Column(name = "sky_id")
  public Short getSkyId() {
    return this.skyId;
  }

  public void setSkyId(Short skyId) {
    this.skyId = skyId;
  }

  @Column(name = "distance", precision = 8, scale = 8)
  public Float getDistance() {
    return this.distance;
  }

  public void setDistance(Float distance) {
    this.distance = distance;
  }

  @Column(name = "deltamag", precision = 8, scale = 8)
  public Float getDeltamag() {
    return this.deltamag;
  }

  public void setDeltamag(Float deltamag) {
    this.deltamag = deltamag;
  }

  @Column(name = "data_produce_method", length = 1)
  public Character getDataProduceMethod() {
    return this.dataProduceMethod;
  }

  public void setDataProduceMethod(Character dataProduceMethod) {
    this.dataProduceMethod = dataProduceMethod;
  }

  /**
   * @return the timeSubSecond
   */
  @Column(name = "time_sub_second")
  public Integer getTimeSubSecond() {
    return timeSubSecond;
  }

  /**
   * @param timeSubSecond the timeSubSecond to set
   */
  public void setTimeSubSecond(Integer timeSubSecond) {
    this.timeSubSecond = timeSubSecond;
  }

  public void printInfo() {
    System.out.println(String.format("%f\t%f\t%f\t%f\t%s\t%f\t%d\t0\t%d",
            this.x, this.y, this.raD, this.decD, this.dateStr, this.magAper, this.ffNumber, this.oorId));
  }

  @Override
  public String toString() {
    return String.format("%f\t%f\t%f\t%f\t%s\t%f\t%d\t0\t%d",
            this.x, this.y, this.raD, this.decD, this.dateStr, this.magAper, this.ffNumber, this.oorId);
  }
}
