package com.gwac.model;
// Generated May 5, 2014 8:56:32 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OtObserveRecordShow generated by hbm2java
 */
@Entity
@Table(name = "ot_observe_record", schema = "public"
)
public class OtObserveRecordShow implements java.io.Serializable {

  private long oorId;
  private Long otId;
  private Long ffId;
  private String ffName;
  private String ffPath;
  private String ffcName;
  private String ffcPath;
  private Long ffcId;
  private Short otTypeId;
  private Float raD;
  private Float decD;
  private Float x;
  private Float y;
  private Float XTemp;
  private Float YTemp;
  private Date dateUt;
  private Float flux;
  private Boolean flag;
  private Float flagChb;
  private Float background;
  private Float threshold;
  private Float magAper;
  private Float magerrAper;
  private Float ellipticity;
  private Float classStar;
  private Boolean otFlag;

  public OtObserveRecordShow() {
  }

  public OtObserveRecordShow(long oorId) {
    this.oorId = oorId;
  }

  public OtObserveRecordShow(long oorId, Long otId, Long ffId, Long ffcId, Short otTypeId, Float raD, Float decD, Float x, Float y, Float XTemp, Float YTemp, Date dateUt, Float flux, Boolean flag, Float flagChb, Float background, Float threshold, Float magAper, Float magerrAper, Float ellipticity, Float classStar, Boolean otFlag) {
    this.oorId = oorId;
    this.otId = otId;
    this.ffId = ffId;
    this.ffcId = ffcId;
    this.otTypeId = otTypeId;
    this.raD = raD;
    this.decD = decD;
    this.x = x;
    this.y = y;
    this.XTemp = XTemp;
    this.YTemp = YTemp;
    this.dateUt = dateUt;
    this.flux = flux;
    this.flag = flag;
    this.flagChb = flagChb;
    this.background = background;
    this.threshold = threshold;
    this.magAper = magAper;
    this.magerrAper = magerrAper;
    this.ellipticity = ellipticity;
    this.classStar = classStar;
    this.otFlag = otFlag;
  }

  @Id
  @Column(name = "oor_id")
  public long getOorId() {
    return this.oorId;
  }

  public void setOorId(long oorId) {
    this.oorId = oorId;
  }

  @Column(name = "ot_id")
  public Long getOtId() {
    return this.otId;
  }

  public void setOtId(Long otId) {
    this.otId = otId;
  }

  @Column(name = "ff_id")
  public Long getFfId() {
    return this.ffId;
  }

  public void setFfId(Long ffId) {
    this.ffId = ffId;
  }

  @Column(name = "ffc_id")
  public Long getFfcId() {
    return this.ffcId;
  }

  public void setFfcId(Long ffcId) {
    this.ffcId = ffcId;
  }

  @Column(name = "ot_type_id")
  public Short getOtTypeId() {
    return this.otTypeId;
  }

  public void setOtTypeId(Short otTypeId) {
    this.otTypeId = otTypeId;
  }

  @Column(name = "ra_d")
  public Float getRaD() {
    return this.raD;
  }

  public void setRaD(Float raD) {
    this.raD = raD;
  }

  @Column(name = "dec_d")
  public Float getDecD() {
    return this.decD;
  }

  public void setDecD(Float decD) {
    this.decD = decD;
  }

  @Column(name = "x")
  public Float getX() {
    return this.x;
  }

  public void setX(Float x) {
    this.x = x;
  }

  @Column(name = "y")
  public Float getY() {
    return this.y;
  }

  public void setY(Float y) {
    this.y = y;
  }

  @Column(name = "x_temp")
  public Float getXTemp() {
    return this.XTemp;
  }

  public void setXTemp(Float XTemp) {
    this.XTemp = XTemp;
  }

  @Column(name = "y_temp")
  public Float getYTemp() {
    return this.YTemp;
  }

  public void setYTemp(Float YTemp) {
    this.YTemp = YTemp;
  }

  @Column(name = "date_ut")
  public Date getDateUt() {
    return this.dateUt;
  }

  public void setDateUt(Date dateUt) {
    this.dateUt = dateUt;
  }

  @Column(name = "flux")
  public Float getFlux() {
    return this.flux;
  }

  public void setFlux(Float flux) {
    this.flux = flux;
  }

  @Column(name = "flag")
  public Boolean getFlag() {
    return this.flag;
  }

  public void setFlag(Boolean flag) {
    this.flag = flag;
  }

  @Column(name = "flag_chb")
  public Float getFlagChb() {
    return this.flagChb;
  }

  public void setFlagChb(Float flagChb) {
    this.flagChb = flagChb;
  }

  @Column(name = "background")
  public Float getBackground() {
    return this.background;
  }

  public void setBackground(Float background) {
    this.background = background;
  }

  @Column(name = "threshold")
  public Float getThreshold() {
    return this.threshold;
  }

  public void setThreshold(Float threshold) {
    this.threshold = threshold;
  }

  @Column(name = "mag_aper")
  public Float getMagAper() {
    return this.magAper;
  }

  public void setMagAper(Float magAper) {
    this.magAper = magAper;
  }

  @Column(name = "magerr_aper")
  public Float getMagerrAper() {
    return this.magerrAper;
  }

  public void setMagerrAper(Float magerrAper) {
    this.magerrAper = magerrAper;
  }

  @Column(name = "ellipticity")
  public Float getEllipticity() {
    return this.ellipticity;
  }

  public void setEllipticity(Float ellipticity) {
    this.ellipticity = ellipticity;
  }

  @Column(name = "class_star")
  public Float getClassStar() {
    return this.classStar;
  }

  public void setClassStar(Float classStar) {
    this.classStar = classStar;
  }

  @Column(name = "ot_flag")
  public Boolean getOtFlag() {
    return this.otFlag;
  }

  public void setOtFlag(Boolean otFlag) {
    this.otFlag = otFlag;
  }

  /**
   * @return the ffName
   */
  @Column(name = "ff_name")
  public String getFfName() {
    return ffName;
  }

  /**
   * @param ffName the ffName to set
   */
  public void setFfName(String ffName) {
    this.ffName = ffName;
  }

  /**
   * @return the ffPath
   */
  @Column(name = "ff_path")
  public String getFfPath() {
    return ffPath;
  }

  /**
   * @param ffPath the ffPath to set
   */
  public void setFfPath(String ffPath) {
    this.ffPath = ffPath;
  }

  /**
   * @return the ffcName
   */
  @Column(name = "ffc_name")
  public String getFfcName() {
    return ffcName;
  }

  /**
   * @param ffcName the ffcName to set
   */
  public void setFfcName(String ffcName) {
    this.ffcName = ffcName;
  }

  /**
   * @return the ffcPath
   */
  @Column(name = "ffc_path")
  public String getFfcPath() {
    return ffcPath;
  }

  /**
   * @param ffcPath the ffcPath to set
   */
  public void setFfcPath(String ffcPath) {
    this.ffcPath = ffcPath;
  }

}
