package com.gwac.model;
// Generated 2015-12-17 20:17:15 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FollowUpObject generated by hbm2java
 */
@Entity
@Table(name = "science_object",
         schema = "public"
)
public class ScienceObject implements java.io.Serializable {
  
  private long soId;
  private String name;
  private Float ra;
  private Float dec;
  private Date discoveryTimeUtc;
  private Date lastObsTimeUtc;
  private Integer followupTimes;
  private String originOrganization;
  private Float mag;
  private String fullName;
  private String type;
  private Boolean isTrue;
  private Integer status;
  
  public ScienceObject() {
  }

  public ScienceObject(long soId) {
    this.soId = soId;
  }

  /**
   * @return the soId
   */
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49")
    ,
    @Parameter(name = "sequence", value = "sci_obj_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "so_id", unique = true, nullable = false)
  public long getSoId() {
    return soId;
  }

  /**
   * @param soId the soId to set
   */
  public void setSoId(long soId) {
    this.soId = soId;
  }

  /**
   * @return the name
   */
  @Column(name = "name")
  public String getName() {
    return name;
  }

  /**
   * @param name the name to set
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * @return the ra
   */
  @Column(name = "ra")
  public Float getRa() {
    return ra;
  }

  /**
   * @param ra the ra to set
   */
  public void setRa(Float ra) {
    this.ra = ra;
  }

  /**
   * @return the dec
   */
  @Column(name = "dec")
  public Float getDec() {
    return dec;
  }

  /**
   * @param dec the dec to set
   */
  public void setDec(Float dec) {
    this.dec = dec;
  }

  /**
   * @return the discoveryTimeUtc
   */
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "discovery_time_utc", length = 29)
  public Date getDiscoveryTimeUtc() {
    return discoveryTimeUtc;
  }

  /**
   * @param discoveryTimeUtc the discoveryTimeUtc to set
   */
  public void setDiscoveryTimeUtc(Date discoveryTimeUtc) {
    this.discoveryTimeUtc = discoveryTimeUtc;
  }

  /**
   * @return the lastObsTimeUtc
   */
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "last_obs_time_utc", length = 29)
  public Date getLastObsTimeUtc() {
    return lastObsTimeUtc;
  }

  /**
   * @param lastObsTimeUtc the lastObsTimeUtc to set
   */
  public void setLastObsTimeUtc(Date lastObsTimeUtc) {
    this.lastObsTimeUtc = lastObsTimeUtc;
  }

  /**
   * @return the followupTimes
   */
  @Column(name = "followup_times")
  public Integer getFollowupTimes() {
    return followupTimes;
  }

  /**
   * @param followupTimes the followupTimes to set
   */
  public void setFollowupTimes(Integer followupTimes) {
    this.followupTimes = followupTimes;
  }

  /**
   * @return the originOrganization
   */
  @Column(name = "origin_organization")
  public String getOriginOrganization() {
    return originOrganization;
  }

  /**
   * @param originOrganization the originOrganization to set
   */
  public void setOriginOrganization(String originOrganization) {
    this.originOrganization = originOrganization;
  }

  /**
   * @return the mag
   */
  @Column(name = "mag")
  public Float getMag() {
    return mag;
  }

  /**
   * @param mag the mag to set
   */
  public void setMag(Float mag) {
    this.mag = mag;
  }

  /**
   * @return the fullName
   */
  @Column(name = "full_name")
  public String getFullName() {
    return fullName;
  }

  /**
   * @param fullName the fullName to set
   */
  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  /**
   * @return the type
   */
  @Column(name = "type")
  public String getType() {
    return type;
  }

  /**
   * @param type the type to set
   */
  public void setType(String type) {
    this.type = type;
  }

  /**
   * @return the isTrue
   */
  @Column(name = "is_true")
  public Boolean getIsTrue() {
    return isTrue;
  }

  /**
   * @param isTrue the isTrue to set
   */
  public void setIsTrue(Boolean isTrue) {
    this.isTrue = isTrue;
  }

  /**
   * @return the status
   */
  @Column(name = "status")
  public Integer getStatus() {
    return status;
  }

  /**
   * @param status the status to set
   */
  public void setStatus(Integer status) {
    this.status = status;
  }

}
