package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SyncFile generated by hbm2java
 */
@Entity
@Table(name="sync_file"
    ,schema="public"
)
public class SyncFile  implements java.io.Serializable {


     private long sfId;
     private String fileName;
     private String path;
     private Date storeTime;
     private Boolean isSync;
     private Boolean isSyncSuccess;

    public SyncFile() {
    }

	
    public SyncFile(long sfId) {
        this.sfId = sfId;
    }
    public SyncFile(long sfId, String fileName, String path, Date storeTime, Boolean isSync, Boolean isSyncSuccess) {
       this.sfId = sfId;
       this.fileName = fileName;
       this.path = path;
       this.storeTime = storeTime;
       this.isSync = isSync;
       this.isSyncSuccess = isSyncSuccess;
    }
   
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "sf_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "sf_id", unique = true, nullable = false)
    public long getSfId() {
        return this.sfId;
    }
    
    public void setSfId(long sfId) {
        this.sfId = sfId;
    }

    
    @Column(name="file_name", length=1024)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="path", length=1024)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="store_time", length=29)
    public Date getStoreTime() {
        return this.storeTime;
    }
    
    public void setStoreTime(Date storeTime) {
        this.storeTime = storeTime;
    }

    
    @Column(name="is_sync")
    public Boolean getIsSync() {
        return this.isSync;
    }
    
    public void setIsSync(Boolean isSync) {
        this.isSync = isSync;
    }

    
    @Column(name="is_sync_success")
    public Boolean getIsSyncSuccess() {
        return this.isSyncSuccess;
    }
    
    public void setIsSyncSuccess(Boolean isSyncSuccess) {
        this.isSyncSuccess = isSyncSuccess;
    }




}


