package com.gwac.model;
// Generated 2017-10-22 23:35:04 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SystemStatusMonitorId generated by hbm2java
 */
@Entity
@Table(name = "system_status_monitor", schema = "public"
)
public class SystemStatusMonitor implements java.io.Serializable {

  private String identity;
  private String regImgName;
  private Date regImgTime;
  private String imgParmName;
  private Date imgParmTime;
  private String ot1ListName;
  private Date ot1ListTime;
  private String imgCutFileName;
  private Date imgCutFileTime;
  private String lookBackOt2Name;
  private Date lookBackOt2Time;
  private String thumbnailName;
  private Date thumbnailTime;
  private String logContent;
  private Date logTime;
  private Long imgParmId;
  private Float camTemperature;
  private String imgFwhm;
  private Float positionError;
  private Float camTemperatureHigh;
  private Integer processMachineStatus;
  private Float processMachineStorage;
  private Float processMachineCpu;
  private Integer captureMachineStatus;
  private Float captureMachineStorage;
  private Float captureMachineCpu;
  private Long opSn;
  private Date opTime;
  private Date processMachineTime;
  private Date captureMachineTime;
  private String ot1ListNameSub;
  private Date ot1ListTimeSub;
  private String imgCutFileNameSub;
  private Date imgCutFileTimeSub;
  private String lookBackOt2NameSub;
  private Date lookBackOt2TimeSub;
  private String imgCutFileRefName;
  private Date imgCutFileRefTime;
  private String imgCutRequestRefName;
  private Date imgCutRequestRefTime;
  private String imgCutRequestName;
  private Date imgCutRequestTime;
  private Integer cameraStatus;

  public SystemStatusMonitor() {
  }

  @Id
  @Column(name = "identity", unique = true, nullable = false)
  public String getIdentity() {
    return this.identity;
  }

  public void setIdentity(String identity) {
    this.identity = identity;
  }

  @Column(name = "reg_img_name")
  public String getRegImgName() {
    return this.regImgName;
  }

  public void setRegImgName(String regImgName) {
    this.regImgName = regImgName;
  }

  @Column(name = "reg_img_time", length = 29)
  public Date getRegImgTime() {
    return this.regImgTime;
  }

  public void setRegImgTime(Date regImgTime) {
    this.regImgTime = regImgTime;
  }

  @Column(name = "img_parm_name")
  public String getImgParmName() {
    return this.imgParmName;
  }

  public void setImgParmName(String imgParmName) {
    this.imgParmName = imgParmName;
  }

  @Column(name = "img_parm_time", length = 29)
  public Date getImgParmTime() {
    return this.imgParmTime;
  }

  public void setImgParmTime(Date imgParmTime) {
    this.imgParmTime = imgParmTime;
  }

  @Column(name = "ot1_list_name")
  public String getOt1ListName() {
    return this.ot1ListName;
  }

  public void setOt1ListName(String ot1ListName) {
    this.ot1ListName = ot1ListName;
  }

  @Column(name = "ot1_list_time", length = 29)
  public Date getOt1ListTime() {
    return this.ot1ListTime;
  }

  public void setOt1ListTime(Date ot1ListTime) {
    this.ot1ListTime = ot1ListTime;
  }

  @Column(name = "img_cut_file_name")
  public String getImgCutFileName() {
    return this.imgCutFileName;
  }

  public void setImgCutFileName(String imgCutFileName) {
    this.imgCutFileName = imgCutFileName;
  }

  @Column(name = "img_cut_file_time", length = 29)
  public Date getImgCutFileTime() {
    return this.imgCutFileTime;
  }

  public void setImgCutFileTime(Date imgCutFileTime) {
    this.imgCutFileTime = imgCutFileTime;
  }

  @Column(name = "look_back_ot2_name")
  public String getLookBackOt2Name() {
    return this.lookBackOt2Name;
  }

  public void setLookBackOt2Name(String lookBackOt2Name) {
    this.lookBackOt2Name = lookBackOt2Name;
  }

  @Column(name = "look_back_ot2_time", length = 29)
  public Date getLookBackOt2Time() {
    return this.lookBackOt2Time;
  }

  public void setLookBackOt2Time(Date lookBackOt2Time) {
    this.lookBackOt2Time = lookBackOt2Time;
  }

  @Column(name = "thumbnail_name")
  public String getThumbnailName() {
    return this.thumbnailName;
  }

  public void setThumbnailName(String thumbnailName) {
    this.thumbnailName = thumbnailName;
  }

  @Column(name = "thumbnail_time", length = 29)
  public Date getThumbnailTime() {
    return this.thumbnailTime;
  }

  public void setThumbnailTime(Date thumbnailTime) {
    this.thumbnailTime = thumbnailTime;
  }

  @Column(name = "log_content")
  public String getLogContent() {
    return this.logContent;
  }

  public void setLogContent(String logContent) {
    this.logContent = logContent;
  }

  @Column(name = "log_time", length = 29)
  public Date getLogTime() {
    return this.logTime;
  }

  public void setLogTime(Date logTime) {
    this.logTime = logTime;
  }

  @Column(name = "img_parm_id")
  public Long getImgParmId() {
    return this.imgParmId;
  }

  public void setImgParmId(Long imgParmId) {
    this.imgParmId = imgParmId;
  }

  @Column(name = "cam_temperature", precision = 8, scale = 8)
  public Float getCamTemperature() {
    return this.camTemperature;
  }

  public void setCamTemperature(Float camTemperature) {
    this.camTemperature = camTemperature;
  }

  @Column(name = "img_fwhm")
  public String getImgFwhm() {
    return this.imgFwhm;
  }

  public void setImgFwhm(String imgFwhm) {
    this.imgFwhm = imgFwhm;
  }

  @Column(name = "position_error", precision = 8, scale = 8)
  public Float getPositionError() {
    return this.positionError;
  }

  public void setPositionError(Float positionError) {
    this.positionError = positionError;
  }

  @Column(name = "cam_temperature_high", precision = 8, scale = 8)
  public Float getCamTemperatureHigh() {
    return this.camTemperatureHigh;
  }

  public void setCamTemperatureHigh(Float camTemperatureHigh) {
    this.camTemperatureHigh = camTemperatureHigh;
  }

  @Column(name = "process_machine_status")
  public Integer getProcessMachineStatus() {
    return this.processMachineStatus;
  }

  public void setProcessMachineStatus(Integer processMachineStatus) {
    this.processMachineStatus = processMachineStatus;
  }

  @Column(name = "process_machine_storage", precision = 8, scale = 8)
  public Float getProcessMachineStorage() {
    return this.processMachineStorage;
  }

  public void setProcessMachineStorage(Float processMachineStorage) {
    this.processMachineStorage = processMachineStorage;
  }

  @Column(name = "process_machine_cpu", precision = 8, scale = 8)
  public Float getProcessMachineCpu() {
    return this.processMachineCpu;
  }

  public void setProcessMachineCpu(Float processMachineCpu) {
    this.processMachineCpu = processMachineCpu;
  }

  @Column(name = "capture_machine_status")
  public Integer getCaptureMachineStatus() {
    return this.captureMachineStatus;
  }

  public void setCaptureMachineStatus(Integer captureMachineStatus) {
    this.captureMachineStatus = captureMachineStatus;
  }

  @Column(name = "capture_machine_storage", precision = 8, scale = 8)
  public Float getCaptureMachineStorage() {
    return this.captureMachineStorage;
  }

  public void setCaptureMachineStorage(Float captureMachineStorage) {
    this.captureMachineStorage = captureMachineStorage;
  }

  @Column(name = "capture_machine_cpu", precision = 8, scale = 8)
  public Float getCaptureMachineCpu() {
    return this.captureMachineCpu;
  }

  public void setCaptureMachineCpu(Float captureMachineCpu) {
    this.captureMachineCpu = captureMachineCpu;
  }

  /**
   * @return the opSn
   */
  @Column(name = "op_sn")
  public Long getOpSn() {
    return opSn;
  }

  /**
   * @param opSn the opSn to set
   */
  public void setOpSn(Long opSn) {
    this.opSn = opSn;
  }

  /**
   * @return the opTime
   */
  @Column(name = "op_time")
  public Date getOpTime() {
    return opTime;
  }

  /**
   * @param opTime the opTime to set
   */
  public void setOpTime(Date opTime) {
    this.opTime = opTime;
  }

  /**
   * @return the processMachineTime
   */
  @Column(name = "process_machine_time")
  public Date getProcessMachineTime() {
    return processMachineTime;
  }

  /**
   * @param processMachineTime the processMachineTime to set
   */
  public void setProcessMachineTime(Date processMachineTime) {
    this.processMachineTime = processMachineTime;
  }

  /**
   * @return the captureMachineTime
   */
  @Column(name = "capture_machine_time")
  public Date getCaptureMachineTime() {
    return captureMachineTime;
  }

  /**
   * @param captureMachineTime the captureMachineTime to set
   */
  public void setCaptureMachineTime(Date captureMachineTime) {
    this.captureMachineTime = captureMachineTime;
  }

  /**
   * @return the ot1ListNameSub
   */
  @Column(name = "ot1_list_name_sub")
  public String getOt1ListNameSub() {
    return ot1ListNameSub;
  }

  /**
   * @param ot1ListNameSub the ot1ListNameSub to set
   */
  public void setOt1ListNameSub(String ot1ListNameSub) {
    this.ot1ListNameSub = ot1ListNameSub;
  }

  /**
   * @return the ot1ListTimeSub
   */
  @Column(name = "ot1_list_time_sub")
  public Date getOt1ListTimeSub() {
    return ot1ListTimeSub;
  }

  /**
   * @param ot1ListTimeSub the ot1ListTimeSub to set
   */
  public void setOt1ListTimeSub(Date ot1ListTimeSub) {
    this.ot1ListTimeSub = ot1ListTimeSub;
  }

  /**
   * @return the imgCutFileNameSub
   */
  @Column(name = "img_cut_file_name_sub")
  public String getImgCutFileNameSub() {
    return imgCutFileNameSub;
  }

  /**
   * @param imgCutFileNameSub the imgCutFileNameSub to set
   */
  public void setImgCutFileNameSub(String imgCutFileNameSub) {
    this.imgCutFileNameSub = imgCutFileNameSub;
  }

  /**
   * @return the imgCutFileTimeSub
   */
  @Column(name = "img_cut_file_time_sub")
  public Date getImgCutFileTimeSub() {
    return imgCutFileTimeSub;
  }

  /**
   * @param imgCutFileTimeSub the imgCutFileTimeSub to set
   */
  public void setImgCutFileTimeSub(Date imgCutFileTimeSub) {
    this.imgCutFileTimeSub = imgCutFileTimeSub;
  }

  /**
   * @return the lookBackOt2NameSub
   */
  @Column(name = "look_back_ot2_name_sub")
  public String getLookBackOt2NameSub() {
    return lookBackOt2NameSub;
  }

  /**
   * @param lookBackOt2NameSub the lookBackOt2NameSub to set
   */
  public void setLookBackOt2NameSub(String lookBackOt2NameSub) {
    this.lookBackOt2NameSub = lookBackOt2NameSub;
  }

  /**
   * @return the lookBackOt2TimeSub
   */
  @Column(name = "look_back_ot2_time_sub")
  public Date getLookBackOt2TimeSub() {
    return lookBackOt2TimeSub;
  }

  /**
   * @param lookBackOt2TimeSub the lookBackOt2TimeSub to set
   */
  public void setLookBackOt2TimeSub(Date lookBackOt2TimeSub) {
    this.lookBackOt2TimeSub = lookBackOt2TimeSub;
  }

  /**
   * @return the imgCutFileRefName
   */
  @Column(name = "img_cut_file_ref_name")
  public String getImgCutFileRefName() {
    return imgCutFileRefName;
  }

  /**
   * @param imgCutFileRefName the imgCutFileRefName to set
   */
  public void setImgCutFileRefName(String imgCutFileRefName) {
    this.imgCutFileRefName = imgCutFileRefName;
  }

  /**
   * @return the imgCutFileRefTime
   */
  @Column(name = "img_cut_file_ref_time")
  public Date getImgCutFileRefTime() {
    return imgCutFileRefTime;
  }

  /**
   * @param imgCutFileRefTime the imgCutFileRefTime to set
   */
  public void setImgCutFileRefTime(Date imgCutFileRefTime) {
    this.imgCutFileRefTime = imgCutFileRefTime;
  }

  /**
   * @return the imgCutRequestRefName
   */
  @Column(name = "img_cut_request_ref_name")
  public String getImgCutRequestRefName() {
    return imgCutRequestRefName;
  }

  /**
   * @param imgCutRequestRefName the imgCutRequestRefName to set
   */
  public void setImgCutRequestRefName(String imgCutRequestRefName) {
    this.imgCutRequestRefName = imgCutRequestRefName;
  }

  /**
   * @return the imgCutRequestRefTime
   */
  @Column(name = "img_cut_request_ref_time")
  public Date getImgCutRequestRefTime() {
    return imgCutRequestRefTime;
  }

  /**
   * @param imgCutRequestRefTime the imgCutRequestRefTime to set
   */
  public void setImgCutRequestRefTime(Date imgCutRequestRefTime) {
    this.imgCutRequestRefTime = imgCutRequestRefTime;
  }

  /**
   * @return the imgCutRequestName
   */
  @Column(name = "img_cut_request_name")
  public String getImgCutRequestName() {
    return imgCutRequestName;
  }

  /**
   * @param imgCutRequestName the imgCutRequestName to set
   */
  public void setImgCutRequestName(String imgCutRequestName) {
    this.imgCutRequestName = imgCutRequestName;
  }

  /**
   * @return the imgCutRequestTime
   */
  @Column(name = "img_cut_request_time")
  public Date getImgCutRequestTime() {
    return imgCutRequestTime;
  }

  /**
   * @param imgCutRequestTime the imgCutRequestTime to set
   */
  public void setImgCutRequestTime(Date imgCutRequestTime) {
    this.imgCutRequestTime = imgCutRequestTime;
  }

  /**
   * @return the cameraStatus
   */
  @Column(name = "camera_status")
  public Integer getCameraStatus() {
    return cameraStatus;
  }

  /**
   * @param cameraStatus the cameraStatus to set
   */
  public void setCameraStatus(Integer cameraStatus) {
    this.cameraStatus = cameraStatus;
  }

}
