package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DataProcessMachine generated by hbm2java
 */
@Entity
@Table(name = "timing_task", schema = "public"
)
public class TimingTask implements java.io.Serializable {

  private long ttId;
  private String ttName;
  private String ttCommand;
  private String dpmName;
  private Date planStartTime;
  private Date planEndTime;
  private Date realEndTime;
  private char status;
  private String comments;
  private String ttFileName;
  private char type;
  private String executePath;
  private Date planStartDate;
  private Date planEndDate;

  public TimingTask() {
  }

  public TimingTask(int ttId) {
    this.ttId = ttId;
  }

  @Override
  public String toString() {
    return "ttName=" + ttName + "\nttCommand=" + ttCommand + "\ndpmName=" + dpmName 
            + "\nplanStartTime=" + planStartTime.toString()
            + "\nplanEndTime=" + planEndTime.toString() + "\nstatus=" + status 
            + "\ncomments=" + comments + "\nttFileName=" + ttFileName
            + "\ntype=" + type + "\nexecutePath=" + executePath + "\nplanStartDate=" 
            + planStartDate.toString() + "\nplanEndDate=" + planEndDate.toString();
  }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "tt_id_seq")})
     @Id 
  @GeneratedValue(generator = "generator")
  @Column(name = "tt_id", unique = true, nullable = false)
  public long getTtId() {
    return this.ttId;
  }

  public void setTtId(long ttId) {
    this.ttId = ttId;
  }

  /**
   * @return the ttName
   */
  @Column(name = "tt_name")
  public String getTtName() {
    return ttName;
  }

  /**
   * @param ttName the ttName to set
   */
  public void setTtName(String ttName) {
    this.ttName = ttName;
  }

  /**
   * @return the ttCommand
   */
  @Column(name = "tt_command")
  public String getTtCommand() {
    return ttCommand;
  }

  /**
   * @param ttCommand the ttCommand to set
   */
  public void setTtCommand(String ttCommand) {
    this.ttCommand = ttCommand;
  }

  /**
   * @return the dpmName
   */
  @Column(name = "dpm_Name")
  public String getDpmName() {
    return dpmName;
  }

  /**
   * @param dpmName the dpmName to set
   */
  public void setDpmName(String dpmName) {
    this.dpmName = dpmName;
  }

  /**
   * @return the planStartTime
   */
  @Column(name = "plan_start_time")
  public Date getPlanStartTime() {
    return planStartTime;
  }

  /**
   * @param planStartTime the planStartTime to set
   */
  public void setPlanStartTime(Date planStartTime) {
    this.planStartTime = planStartTime;
  }

  /**
   * @return the planEndTime
   */
  @Column(name = "plan_end_time")
  public Date getPlanEndTime() {
    return planEndTime;
  }

  /**
   * @param planEndTime the planEndTime to set
   */
  public void setPlanEndTime(Date planEndTime) {
    this.planEndTime = planEndTime;
  }

  /**
   * @return the realEndTime
   */
  @Column(name = "real_end_time")
  public Date getRealEndTime() {
    return realEndTime;
  }

  /**
   * @param realEndTime the realEndTime to set
   */
  public void setRealEndTime(Date realEndTime) {
    this.realEndTime = realEndTime;
  }

  /**
   * @return the status
   */
  @Column(name = "status")
  public char getStatus() {
    return status;
  }

  /**
   * @param status the status to set
   */
  public void setStatus(char status) {
    this.status = status;
  }

  /**
   * @return the comments
   */
  @Column(name = "comments")
  public String getComments() {
    return comments;
  }

  /**
   * @param comments the comments to set
   */
  public void setComments(String comments) {
    this.comments = comments;
  }

  /**
   * @return the ttFileName
   */
  @Column(name = "tt_file_name")
  public String getTtFileName() {
    return ttFileName;
  }

  /**
   * @param ttFileName the ttFileName to set
   */
  public void setTtFileName(String ttFileName) {
    this.ttFileName = ttFileName;
  }

  /**
   * @return the type
   */
  @Column(name = "type")
  public char getType() {
    return type;
  }

  /**
   * @param type the type to set
   */
  public void setType(char type) {
    this.type = type;
  }

  /**
   * @return the executePath
   */
  @Column(name = "execute_path")
  public String getExecutePath() {
    return executePath;
  }

  /**
   * @param executePath the executePath to set
   */
  public void setExecutePath(String executePath) {
    this.executePath = executePath;
  }

  /**
   * @return the planStartDate
   */
  @Column(name = "plan_start_date")
  public Date getPlanStartDate() {
    return planStartDate;
  }

  /**
   * @param planStartDate the planStartDate to set
   */
  public void setPlanStartDate(Date planStartDate) {
    this.planStartDate = planStartDate;
  }

  /**
   * @return the planEndDate
   */
  @Column(name = "plan_end_date")
  public Date getPlanEndDate() {
    return planEndDate;
  }

  /**
   * @param planEndDate the planEndDate to set
   */
  public void setPlanEndDate(Date planEndDate) {
    this.planEndDate = planEndDate;
  }

}
