package com.gwac.model;
// Generated 2015-10-2 9:40:37 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DataProcessMachine generated by hbm2java
 */
@Entity
@Table(name = "timing_task_log", schema = "public"
)
public class TimingTaskLog implements java.io.Serializable {

  /**
   * @return the ttId
   */
  @Column(name = "tt_id")
  public String getTtId() {
    return ttId;
  }

  /**
   * @param ttId the ttId to set
   */
  public void setTtId(String ttId) {
    this.ttId = ttId;
  }

  /**
   * @return the content
   */
  @Column(name = "content")
  public String getContent() {
    return content;
  }

  /**
   * @param content the content to set
   */
  public void setContent(String content) {
    this.content = content;
  }

  /**
   * @return the time
   */
  @Column(name = "time")
  public Date getTime() {
    return time;
  }

  /**
   * @param time the time to set
   */
  public void setTime(Date time) {
    this.time = time;
  }

  private int ttlId;
  private String ttId;
  private String content;
  private Date time;

  public TimingTaskLog() {
  }

  public TimingTaskLog(int ttlId) {
    this.ttlId = ttlId;
  }

  @Id
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ttl_seq")
  @SequenceGenerator(name = "ttl_seq", sequenceName = "ttl_id_seq")
  @Column(name = "ttl_id", unique = true, nullable = false)
  public int getTtlId() {
    return this.ttlId;
  }

  public void setTtlId(int ttlId) {
    this.ttlId = ttlId;
  }

}
