package com.gwac.model;
// Generated 2015-11-5 20:06:22 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * UserActionLog generated by hbm2java
 */
@Entity
@Table(name="user_action_log"
    ,schema="public"
)
public class UserActionLog  implements java.io.Serializable {


     private long ualId;
     private Integer uiId;
     private Short uaId;
     private Date ualTime;

    public UserActionLog() {
    }

	
    public UserActionLog(long ualId) {
        this.ualId = ualId;
    }
    public UserActionLog(long ualId, Integer uiId, Short uaId, Date ualTime) {
       this.ualId = ualId;
       this.uiId = uiId;
       this.uaId = uaId;
       this.ualTime = ualTime;
    }
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "ual_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
    @Column(name="ual_id", unique=true, nullable=false)
    public long getUalId() {
        return this.ualId;
    }
    
    public void setUalId(long ualId) {
        this.ualId = ualId;
    }

    
    @Column(name="ui_id")
    public Integer getUiId() {
        return this.uiId;
    }
    
    public void setUiId(Integer uiId) {
        this.uiId = uiId;
    }

    
    @Column(name="ua_id")
    public Short getUaId() {
        return this.uaId;
    }
    
    public void setUaId(Short uaId) {
        this.uaId = uaId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ual_time", length=29)
    public Date getUalTime() {
        return this.ualTime;
    }
    
    public void setUalTime(Date ualTime) {
        this.ualTime = ualTime;
    }




}


